export const cheniceProducts = [
  {
    id: 1,
    title: "CARTELLA COLORI Liposome Hair Color - BIG",
    price: 65.0,
    format: "1 PEZZO",
    subsubCategory: "ACCESSORI",
    category: 'Capelli',
    brand: 'Chenice',
    newFlag: true,
    favorite: true,
    selected: true,
    image: '/products/image-3.jpg',
    region: ['Abruzzo', 'Lazio']
  },
  {
    title: "CARTELLA COLORI Liposome Hair Color - SMALL",
    price: 23.5,
    format: "1 PEZZO",
    subCategory: "ACCESSORI",
    category: 'Capelli',
    brand: 'Chenice',
    newFlag: true,
    favorite: true,
    selected: true,
    image: '/products/image-3.jpg',
    region: ['Abruzzo', 'Lazio']
  },
  {
    title: "BACINELLA Liposome Hair Color",
    price: 1.4,
    format: "1 PEZZO",
    subCategory: "ACCESSORI",
    category: 'Capelli',
    brand: 'Chenice',
    newFlag: true,
    favorite: true,
    selected: true,
    image: '/products/image-3.jpg',
    region: ['Abruzzo', 'Lazio']
  },
  {
    title: "PENNELLO Liposome Hair Color",
    price: 1.25,
    format: "1 PEZZO",
    subCategory: "ACCESSORI",
    category: 'Capelli',
    brand: 'Chenice',
    newFlag: true,
    favorite: true,
    selected: true,
    image: '/products/image-3.jpg',
    region: ['Abruzzo', 'Lazio']
  },
  {
    title: "CARTELLA COLORI Botanical",
    price: 43.0,
    format: "1 PEZZO",
    subCategory: "ACCESSORI",
    category: 'Capelli',
    brand: 'Chenice',
    newFlag: true,
    favorite: true,
    selected: true,
    image: '/products/image-3.jpg',
    region: ['Abruzzo', 'Lazio']
  },
  {
    title: "MANTELLINE MONOUSO",
    price: 5.5,
    format: "Confezione 30 pz",
    subCategory: "ACCESSORI",
    category: 'Capelli',
    brand: 'Chenice',
    newFlag: true,
    favorite: true,
    selected: true,
    image: '/products/image-3.jpg',
    region: ['Abruzzo', 'Lazio']
  },
  {
    title: "PHON CHENICE",
    price: 89.0,
    format: "1 PEZZO",
    subCategory: "ACCESSORI",
    category: 'Capelli',
    brand: 'Chenice',
    newFlag: true,
    favorite: true,
    selected: true,
    image: '/products/image-3.jpg',
    region: ['Abruzzo', 'Lazio']
  },
  {
    title: "FERRO ARRICCIACAPELLI",
    price: 158.0,
    format: "1 PEZZO",
    subCategory: "ACCESSORI",

    category: 'Capelli',
    brand: 'Chenice',
    newFlag: true,
    favorite: true,
    selected: true,
    image: '/products/image-3.jpg',
    region: ['Abruzzo', 'Lazio']
  },
  {
    title: "ANTI-AGE C18 100 ml.",
    price: 39.5,
    format: "6 FLACONE",
    subCategory: "ANTI-AGE",
    category: 'Capelli',
    brand: 'Chenice',
    newFlag: true,
    favorite: true,
    selected: true,
    image: '/products/image-3.jpg',
    region: ['Abruzzo', 'Lazio']
  },
  {
    title: "ANTI-AGE C18 50 ml.",
    price: 28.0,
    format: "6 FLACONE",
    subCategory: "ANTI-AGE",
    category: 'Capelli',
    brand: 'Chenice',
    newFlag: true,
    favorite: true,
    selected: true,
    image: '/products/image-3.jpg',
    region: ['Abruzzo', 'Lazio']
  },
  {
    title: "DISPLAY ANTI-AGE",
    price: 16.0,
    format: "1 PEZZO",
    subCategory: "ANTI-AGE",
    category: 'Capelli',
    brand: 'Chenice',
    newFlag: true,
    favorite: true,
    selected: true,
    image: '/products/image-3.jpg',
    region: ['Abruzzo', 'Lazio']
  },
  {
    title: "POSTER ANTI-AGE",
    price: 1.9,
    format: "1 PEZZO",
    subCategory: "ANTI-AGE",
    category: 'Capelli',
    brand: 'Chenice',
    newFlag: true,
    favorite: true,
    selected: true,
    image: '/products/image-3.jpg',
    region: ['Abruzzo', 'Lazio']
  },
  {
    title: "DEPLIANT ANTI-AGE",
    price: 2.4,
    format: "1 PEZZO",
    subCategory: "ANTI-AGE",

    category: 'Capelli',
    brand: 'Chenice',
    newFlag: true,
    favorite: true,
    selected: true,
    image: '/products/image-3.jpg',
    region: ['Abruzzo', 'Lazio']
  },
  {
    title: "KIT GREEN CARE",
    price: 55.0,
    format: "1 KIT",
    subCategory: "GREEN CARE",
    category: 'Capelli',
    brand: 'Chenice',
    newFlag: true,
    favorite: true,
    selected: true,
    image: '/products/image-3.jpg',
    region: ['Abruzzo', 'Lazio']
  },
  {
    title: "SANITIZING TREATMENT NR 1 100ml",
    price: 96.0,
    format: "6 FLACONE",
    subCategory: "GREEN CARE",
    category: 'Capelli',
    brand: 'Chenice',
    newFlag: true,
    favorite: true,
    selected: true,
    image: '/products/image-3.jpg',
    region: ['Abruzzo', 'Lazio']
  },
  {
    title: "VITAMIN SHAMPOO NR 2 250ml",
    price: 108.0,
    format: "6 FLACONE",
    subCategory: "GREEN CARE",
    category: 'Capelli',
    brand: 'Chenice',
    newFlag: true,
    favorite: true,
    selected: true,
    image: '/products/image-3.jpg',
    region: ['Abruzzo', 'Lazio']
  },
  {
    title: "VITAMIN LOTION NR 3 100ml",
    price: 126.0,
    format: "6 FLACONE",
    subCategory: "GREEN CARE",
    category: 'Capelli',
    brand: 'Chenice',
    newFlag: true,
    favorite: true,
    selected: true,
    image: '/products/image-3.jpg',
    region: ['Abruzzo', 'Lazio']
  },
  {
    title: "DEPLIANT GREEN CARE",
    price: 2.4,
    format: "1 PEZZO",
    subCategory: "GREEN CARE",
    category: 'Capelli',
    brand: 'Chenice',
    newFlag: true,
    favorite: true,
    selected: true,
    image: '/products/image-3.jpg',
    region: ['Abruzzo', 'Lazio']
  },
  {
    title: "BIOLOGICAL WAVING SYSTEM 100 ml",
    price: 19.5,
    format: "1 KIT (PERM+NEUTR)",
    subCategory: "BIOLOGICAL WAVING SYSTEM",
    category: 'Capelli',
    brand: 'Chenice',
    newFlag: true,
    favorite: true,
    selected: true,
    image: '/products/image-3.jpg',
    region: ['Abruzzo', 'Lazio']
  },
  {
    title: "BROCHURE BWS",
    price: 2.45,
    format: "1 PEZZO",
    subCategory: "BIOLOGICAL WAVING SYSTEM",
    category: 'Capelli',
    brand: 'Chenice',
    newFlag: true,
    favorite: true,
    selected: true,
    image: '/products/image-3.jpg',
    region: ['Abruzzo', 'Lazio']
  },
  {
    title: "POSTER BWS",
    price: 1.8,
    format: "1 PEZZO",
    subCategory: "BIOLOGICAL WAVING SYSTEM",
    category: 'Capelli',
    brand: 'Chenice',
    newFlag: true,
    favorite: true,
    selected: true,
    image: '/products/image-3.jpg',
    region: ['Abruzzo', 'Lazio']
  },
  {
    title: "AQUA WAX 100 ml",
    price: 15.0,
    format: "6 VASO",
    subCategory: "IFIX",
    category: 'Capelli',
    brand: 'Chenice',
    newFlag: true,
    favorite: true,
    selected: true,
    image: '/products/image-3.jpg',
    region: ['Abruzzo', 'Lazio']
  },
  {
    title: "CURLS WAVE 100 ml",
    price: 14.8,
    format: "6 VASO",
    subCategory: "IFIX",
    category: 'Capelli',
    brand: 'Chenice',
    newFlag: true,
    favorite: true,
    selected: true,
    image: '/products/image-3.jpg',
    region: ['Abruzzo', 'Lazio']
  },
  {
    title: "SHAPE-IT 100 ml",
    price: 16.5,
    format: "6 VASO",
    subCategory: "IFIX",
    category: 'Capelli',
    brand: 'Chenice',
    newFlag: true,
    favorite: true,
    selected: true,
    image: '/products/image-3.jpg',
    region: ['Abruzzo', 'Lazio']
  },
  {
    title: "FIX IT GEL 200 ml",
    price: 16.0,
    format: "6 TUBO",
    subCategory: "IFIX",
    category: 'Capelli',
    brand: 'Chenice',
    newFlag: true,
    favorite: true,
    selected: true,
    image: '/products/image-3.jpg',
    region: ['Abruzzo', 'Lazio']
  },
  {
    title: "WET LOOK GEL 200 ml",
    price: 12.0,
    format: "6 TUBO",
    subCategory: "IFIX",
    category: 'Capelli',
    brand: 'Chenice',
    newFlag: true,
    favorite: true,
    selected: true,
    image: '/products/image-3.jpg',
    region: ['Abruzzo', 'Lazio']
  },
  {
    title: "FORMING LACQUER Strong 300 ml",
    price: 19.5,
    format: "12 BOMBOLA",
    subCategory: "IFIX",
    category: 'Capelli',
    brand: 'Chenice',
    newFlag: true,
    favorite: true,
    selected: true,
    image: '/products/image-3.jpg',
    region: ['Abruzzo', 'Lazio']
  },
  {
    title: "VOLUMIZING MOUSSE Strong 300 ml",
    price: 16.5,
    format: "12 BOMBOLA",
    subCategory: "IFIX",
    category: 'Capelli',
    brand: 'Chenice',
    newFlag: true,
    favorite: true,
    selected: true,
    image: '/products/image-3.jpg',
    region: ['Abruzzo', 'Lazio']
  },
  {
    title: "POWER SHINE 500 ml",
    price: 19.0,
    format: "12 BOMBOLA",
    subCategory: "IFIX",
    category: 'Capelli',
    brand: 'Chenice',
    newFlag: true,
    favorite: true,
    selected: true,
    image: '/products/image-3.jpg',
    region: ['Abruzzo', 'Lazio']
  },
  {
    title: "POWER SHINE 75 ml",
    price: 5.95,
    format: "12 BOMBOLA",
    subCategory: "IFIX",
    category: 'Capelli',
    brand: 'Chenice',
    newFlag: true,
    favorite: true,
    selected: true,
    image: '/products/image-3.jpg',
    region: ['Abruzzo', 'Lazio']
  },
  {
    title: "FORMING GLAZE 150 ml",
    price: 13.0,
    format: "6 FLACONE",
    subCategory: "IFIX",
    category: 'Capelli',
    brand: 'Chenice',
    newFlag: true,
    favorite: true,
    selected: true,
    image: '/products/image-3.jpg',
    region: ['Abruzzo', 'Lazio']
  },
  {
    title: "PURE VOLUME 150 ml",
    price: 14.8,
    format: "6 FLACONE",
    subCategory: "IFIX",
    category: 'Capelli',
    brand: 'Chenice',
    newFlag: true,
    favorite: true,
    selected: true,
    image: '/products/image-3.jpg',
    region: ['Abruzzo', 'Lazio']
  },
  {
    title: "POLISHING SERUM 150 ml",
    price: 28.0,
    format: "6 FLACONE",
    subCategory: "IFIX",
    category: 'Capelli',
    brand: 'Chenice',
    newFlag: true,
    favorite: true,
    selected: true,
    image: '/products/image-3.jpg',
    region: ['Abruzzo', 'Lazio']
  },
  {
    title: "PURIFYING SHAMPOO 1 lt",
    price: 28.0,
    format: "1 lt. 6 FLACONE",
    subCategory: "URBN",
    category: 'Capelli',
    brand: 'Chenice',
    newFlag: true,
    favorite: true,
    selected: true,
    image: '/products/image-3.jpg',
    region: ['Abruzzo', 'Lazio']
  },
  {
    title: "PURIFYING MASK 1 lt",
    price: 29.0,
    format: "1 lt. 6 FLACONE",
    subCategory: "URBN",
    category: 'Capelli',
    brand: 'Chenice',
    newFlag: true,
    favorite: true,
    selected: true,
    image: '/products/image-3.jpg',
    region: ['Abruzzo', 'Lazio']
  },
  {
    title: "PURIFYING SHAMPOO 250 ml",
    price: 13.5,
    format: "250 ml. 6 FLACONE",
    subCategory: "URBN",
    category: 'Capelli',
    brand: 'Chenice',
    newFlag: true,
    favorite: true,
    selected: true,
    image: '/products/image-3.jpg',
    region: ['Abruzzo', 'Lazio']
  },
  {
    title: "PURIFYING MASK 200 ml",
    price: 14.0,
    format: "200 ml. 6 FLACONE",
    subCategory: "URBN",
    category: 'Capelli',
    brand: 'Chenice',
    newFlag: true,
    favorite: true,
    selected: true,
    image: '/products/image-3.jpg',
    region: ['Abruzzo', 'Lazio']
  },
  {
    title: "NOURISHING MOUSSE 200 ml",
    price: 21.0,
    format: "200 ml. 6 FLACONE",
    subCategory: "URBN",
    category: 'Capelli',
    brand: 'Chenice',
    newFlag: true,
    favorite: true,
    selected: true,
    image: '/products/image-3.jpg',
    region: ['Abruzzo', 'Lazio']
  },
  {
    title: "NEW URBN WHYTWELVE 150 ml",
    price: 13.0,
    format: "150 ml. 6 FLACONE",
    subCategory: "URBN",
    category: 'Capelli',
    brand: 'Chenice',
    newFlag: true,
    favorite: true,
    selected: true,
    image: '/products/image-3.jpg',
    region: ['Abruzzo', 'Lazio']
  },
  {
    title: "URBN DISPLAY 1 PEZZO",
    price: 13.0,
    format: "1 PEZZO",
    subCategory: "URBN",
    category: 'Capelli',
    brand: 'Chenice',
    newFlag: true,
    favorite: true,
    selected: true,
    image: '/products/image-3.jpg',
    region: ['Abruzzo', 'Lazio']
  },
  {
    title: "URBN BANNER 1 PEZZO",
    price: 25.0,
    format: "1 PEZZO",
    subCategory: "URBN",
    category: 'Capelli',
    brand: 'Chenice',
    newFlag: true,
    favorite: true,
    selected: true,
    image: '/products/image-3.jpg',
    region: ['Abruzzo', 'Lazio']
  },
  {
    title: "URBN POSTER 1 PEZZO",
    price: 1.8,
    format: "1 PEZZO",
    subCategory: "URBN",
    category: 'Capelli',
    brand: 'Chenice',
    newFlag: true,
    favorite: true,
    selected: true,
    image: '/products/image-3.jpg',
    region: ['Abruzzo', 'Lazio']
  },
  {
    title: "URBN BROCHURE 1 PEZZO",
    price: 2.4,
    format: "1 PEZZO",
    subCategory: "URBN",
    category: 'Capelli',
    brand: 'Chenice',
    newFlag: true,
    favorite: true,
    selected: true,
    image: '/products/image-3.jpg',
    region: ['Abruzzo', 'Lazio']
  },
  {
    title: "KIT BOTTOX 50 ml",
    price: 143.0,
    format: "1 KIT",
    subCategory: "BOTTOX EFFECT LOTION",
    category: 'Capelli',
    brand: 'Chenice',
    newFlag: true,
    favorite: true,
    selected: true,
    image: '/products/image-3.jpg',
    region: ['Abruzzo', 'Lazio']
  },
  {
    title: "CLARIFYING SHAMPOO 500 ml.",
    price: 17.0,
    format: "1 PEZZO",
    subCategory: "BOTTOX EFFECT LOTION",
    category: 'Capelli',
    brand: 'Chenice',
    newFlag: true,
    favorite: true,
    selected: true,
    image: '/products/image-3.jpg',
    region: ['Abruzzo', 'Lazio']
  },
  {
    title: "POSTER BOTTOX 1 PEZZO",
    price: 1.85,
    format: "1 PEZZO",
    subCategory: "BOTTOX EFFECT LOTION",
    category: 'Capelli',
    brand: 'Chenice',
    newFlag: true,
    favorite: true,
    selected: true,
    image: '/products/image-3.jpg',
    region: ['Abruzzo', 'Lazio']
  },
  {
    title: "DEPLIANT BOTTOX 1 PEZZO",
    price: 2.35,
    format: "1 PEZZO",
    subCategory: "BOTTOX EFFECT LOTION",
    category: 'Capelli',
    brand: 'Chenice',
    newFlag: true,
    favorite: true,
    selected: true,
    image: '/products/image-3.jpg',
    region: ['Abruzzo', 'Lazio']
  },
  {
    title: "KEEP IN COLOR MOISTURIZING SHAMPOO",
    formato: "1 Lt.",
    precio: "€ 28,00",
    subCategory: "KEEP IN COLOR MOISTURIZING",
    category: 'Capelli',
    brand: 'Chenice',
    newFlag: true,
    favorite: true,
    selected: true,
    image: '/products/image-3.jpg',
    region: ['Abruzzo', 'Lazio']
  },
  {
    title: "KEEP IN COLOR MOISTURIZING MASK",
    formato: "1 Lt.",
    precio: "€ 34,00",
    subCategory: "KEEP IN COLOR MOISTURIZING",
    category: 'Capelli',
    brand: 'Chenice',
    newFlag: true,
    favorite: true,
    selected: true,
    image: '/products/image-3.jpg',
    region: ['Abruzzo', 'Lazio']
  },
  {
    title: "KEEP IN COLOR MOISTURIZING SHAMPOO",
    formato: "250 ml",
    precio: "€ 14,80",
    subCategory: "KEEP IN COLOR MOISTURIZING",
    category: 'Capelli',
    brand: 'Chenice',
    newFlag: true,
    favorite: true,
    selected: true,
    image: '/products/image-3.jpg',
    region: ['Abruzzo', 'Lazio']
  },
  {
    title: "KEEP IN COLOR MOISTURIZING MASK",
    formato: "200 ml",
    precio: "€ 15,00",
    subCategory: "KEEP IN COLOR MOISTURIZING",
    category: 'Capelli',
    brand: 'Chenice',
    newFlag: true,
    favorite: true,
    selected: true,
    image: '/products/image-3.jpg',
    region: ['Abruzzo', 'Lazio']
  },
  {
    title: "BLISTERS KEEP IN COLOR MOISTURIZING",
    formato: "1 PEZZO",
    precio: "€ 1,20",
    subCategory: "KEEP IN COLOR MOISTURIZING",
    category: 'Capelli',
    brand: 'Chenice',
    newFlag: true,
    favorite: true,
    selected: true,
    image: '/products/image-3.jpg',
    region: ['Abruzzo', 'Lazio']
  },
  {
    title: "BROCHURE KEEP IN COLOR MOISTURIZING",
    formato: "1 PEZZO",
    precio: "€ 2,40",
    subCategory: "KEEP IN COLOR MOISTURIZING",
    category: 'Capelli',
    brand: 'Chenice',
    newFlag: true,
    favorite: true,
    selected: true,
    image: '/products/image-3.jpg',
    region: ['Abruzzo', 'Lazio']
  },
  {
    title: "POSTER KEEP IN COLOR MOISTURIZING",
    formato: "1 PEZZO",
    precio: "€ 1,80",
    subCategory: "KEEP IN COLOR MOISTURIZING",
    category: 'Capelli',
    brand: 'Chenice',
    newFlag: true,
    favorite: true,
    selected: true,
    image: '/products/image-3.jpg',
    region: ['Abruzzo', 'Lazio']
  },
  {
    title: "SINERGY WASH",
    formato: "1000 ml",
    precio: "€ 29,50",
    subCategory: "FORFORA-GRASSO",
    category: 'Capelli',
    brand: 'Chenice',
    newFlag: true,
    favorite: true,
    selected: true,
    image: '/products/image-3.jpg',
    region: ['Abruzzo', 'Lazio']
  },
  {
    title: "SINERGY WASH",
    formato: "250 ml",
    precio: "€ 16,50",
    subCategory: "FORFORA-GRASSO",
    category: 'Capelli',
    brand: 'Chenice',
    newFlag: true,
    favorite: true,
    selected: true,
    image: '/products/image-3.jpg',
    region: ['Abruzzo', 'Lazio']
  },
  {
    title: "REGAL WASH",
    formato: "1000 ml",
    precio: "€ 25,00",
    subCategory: "ANTICADUTA",
    category: 'Capelli',
    brand: 'Chenice',
    newFlag: true,
    favorite: true,
    selected: true,
    image: '/products/image-3.jpg',
    region: ['Abruzzo', 'Lazio']
  },
  {
    title: "REGAL WASH",
    formato: "250 ml",
    precio: "€ 13,00",
    subCategory: "ANTICADUTA",
    category: 'Capelli',
    brand: 'Chenice',
    newFlag: true,
    favorite: true,
    selected: true,
    image: '/products/image-3.jpg',
    region: ['Abruzzo', 'Lazio']
  },
  {
    title: "REGAL WASH",
    formato: "100 ml",
    precio: "€ 6,00",
    subCategory: "ANTICADUTA",
    category: 'Capelli',
    brand: 'Chenice',
    newFlag: true,
    favorite: true,
    selected: true,
    image: '/products/image-3.jpg',
    region: ['Abruzzo', 'Lazio']
  },
  {
    title: "REGAL LIFE",
    formato: "12 x 6 ml",
    precio: "€ 42,00",
    subCategory: "ANTICADUTA",
    category: 'Capelli',
    brand: 'Chenice',
    newFlag: true,
    favorite: true,
    selected: true,
    image: '/products/image-3.jpg',
    region: ['Abruzzo', 'Lazio']
  },
  {
    title: "REGAL LIFE",
    formato: "4 x 6 ml",
    precio: "€ 18,00",
    subCategory: "ANTICADUTA",
    category: 'Capelli',
    brand: 'Chenice',
    newFlag: true,
    favorite: true,
    selected: true,
    image: '/products/image-3.jpg',
    region: ['Abruzzo', 'Lazio']
  },
  {
    title: "HYDRO-KERATIN SHAMPOO",
    formato: "1000 ml",
    precio: "€ 26,00",
    subCategory: "RICOSTRUZIONE",
    category: 'Capelli',
    brand: 'Chenice',
    newFlag: true,
    favorite: true,
    selected: true,
    image: '/products/image-3.jpg',
    region: ['Abruzzo', 'Lazio']
  },
  {
    title: "MULTI-VITAMIN OIL",
    formato: "500 ml",
    precio: "€ 31,00",
    subCategory: "RICOSTRUZIONE",
    category: 'Capelli',
    brand: 'Chenice',
    newFlag: true,
    favorite: true,
    selected: true,
    image: '/products/image-3.jpg',
    region: ['Abruzzo', 'Lazio']
  },
  {
    title: "KERABONDING MASK",
    formato: "500 ml",
    precio: "€ 23,00",
    subCategory: "RICOSTRUZIONE",
    category: 'Capelli',
    brand: 'Chenice',
    newFlag: true,
    favorite: true,
    selected: true,
    image: '/products/image-3.jpg',
    region: ['Abruzzo', 'Lazio']
  },
  {
    title: "HYDRO-KERATIN SHAMPOO",
    formato: "250 ml",
    precio: "€ 13,00",
    subCategory: "RICOSTRUZIONE",
    category: 'Capelli',
    brand: 'Chenice',
    newFlag: true,
    favorite: true,
    selected: true,
    image: '/products/image-3.jpg',
    region: ['Abruzzo', 'Lazio']
  },
  {
    title: "MULTI-VITAMIN OIL",
    formato: "150 ml",
    precio: "€ 25,00",
    subCategory: "RICOSTRUZIONE",
    category: 'Capelli',
    brand: 'Chenice',
    newFlag: true,
    favorite: true,
    selected: true,
    image: '/products/image-3.jpg',
    region: ['Abruzzo', 'Lazio']
  },
  {
    title: "KERABONDING MASK",
    formato: "200 ml",
    precio: "€ 14,50",
    subCategory: "RICOSTRUZIONE",
    category: 'Capelli',
    brand: 'Chenice',
    newFlag: true,
    favorite: true,
    selected: true,
    image: '/products/image-3.jpg',
    region: ['Abruzzo', 'Lazio']
  },
  {
    title: "HAIR COLOR ACCELERATOR",
    formato: "1 SC x 4Flaconi",
    precio: "€ 59,00",
    subCategory: "HAIR COLOR ACCELERATOR",
    category: 'Capelli',
    brand: 'Chenice',
    newFlag: true,
    favorite: true,
    selected: true,
    image: '/products/image-3.jpg',
    region: ['Abruzzo', 'Lazio']
  },
  {
    title: "PEACH SHAMPOO",
    formato: "10 lt. 1 FUSTINO",
    precio: "€ 116,00",
    subCategory: "UNDEFINED",
    category: 'Capelli',
    brand: 'Chenice',
    newFlag: true,
    favorite: true,
    selected: true,
    image: '/products/image-3.jpg',
    region: ['Abruzzo', 'Lazio']
  },
  {
    title: "LIPOSOME HAIR COLOR con ACQUA TERMALE",
    formato: "100ml. 6 TUBO",
    precio: "€ 11,50",
    subCategory: "UNDEFINED",
    category: 'Capelli',
    brand: 'Chenice',
    newFlag: true,
    favorite: true,
    selected: true,
    image: '/products/image-3.jpg',
    region: ['Abruzzo', 'Lazio']
  },
  {
    title: "BOTANICAL HAIR COLOR",
    formato: "100ml. 6 TUBO",
    precio: "€ 12,00",
    subCategory: "UNDEFINED",
    category: 'Capelli',
    brand: 'Chenice',
    newFlag: true,
    favorite: true,
    selected: true,
    image: '/products/image-3.jpg',
    region: ['Abruzzo', 'Lazio']
  },
  {
    title: "VITAMIN COLORS",
    formato: "125ml. 3 FLACONE",
    precio: "€ 21,00",
    subCategory: "UNDEFINED",
    category: 'Capelli',
    brand: 'Chenice',
    newFlag: true,
    favorite: true,
    selected: true,
    image: '/products/image-3.jpg',
    region: ['Abruzzo', 'Lazio']
  },
  {
    title: "OXICREME 20 - 30 - 40 vol. - Active Lotion",
    formato: "1 lt. 6 FLACONE",
    precio: "€ 12,50",
    subCategory: "UNDEFINED",
    category: 'Capelli',
    brand: 'Chenice',
    newFlag: true,
    favorite: true,
    selected: true,
    image: '/products/image-3.jpg',
    region: ['Abruzzo', 'Lazio']
  },
  {
    title: "BLEACH POWDER",
    formato: "500 gr. 1 PEZZO",
    precio: "€ 35,00",
    subCategory: "UNDEFINED",
    category: 'Capelli',
    brand: 'Chenice',
    newFlag: true,
    favorite: true,
    selected: true,
    image: '/products/image-3.jpg',
    region: ['Abruzzo', 'Lazio']
  },
  {
    title: "BLEACH POWDER PLUS",
    formato: "500 gr. 1 PEZZO",
    precio: "€ 36,00",
    subCategory: "UNDEFINED",
    category: 'Capelli',
    brand: 'Chenice',
    newFlag: true,
    favorite: true,
    selected: true,
    image: '/products/image-3.jpg',
    region: ['Abruzzo', 'Lazio']
  },
  {
    title: "DARK DIAMOND",
    formato: "500 gr. 1 PEZZO",
    precio: "€ 37,00",
    subCategory: "UNDEFINED",
    category: 'Capelli',
    brand: 'Chenice',
    newFlag: true,
    favorite: true,
    selected: true,
    image: '/products/image-3.jpg',
    region: ['Abruzzo', 'Lazio']
  },
];
