export const eugenpermaProducts = [
  // Lista de productos...
  {
    category: "ACCESSORI",
    product: "CARTELLA COLORI Liposome Hair Color - BIG",
    format: "1 PEZZO",
    price: 65.0,
  },
  {
    category: "ACCESSORI",
    product: "CARTELLA COLORI Liposome Hair Color - SMALL",
    format: "1 PEZZO",
    price: 23.5,
  },
  {
    category: "ACCESSORI",
    product: "BACINELLA Liposome Hair Color",
    format: "1 PEZZO",
    price: 1.4,
  },
  {
    category: "ACCESSORI",
    product: "PENNELLO Liposome Hair Color",
    format: "1 PEZZO",
    price: 1.25,
  },
  {
    category: "ACCESSORI",
    product: "CARTELLA COLORI Botanical",
    format: "1 PEZZO",
    price: 43.0,
  },
  {
    category: "ACCESSORI",
    product: "MANTELLINE MONOUSO",
    format: "Confezione 30 pz",
    price: 5.5,
  },
  {
    category: "ACCESSORI",
    product: "PHON CHENICE",
    format: "1 PEZZO",
    price: 89.0,
  },
  {
    category: "ACCESSORI",
    product: "FERRO ARRICCIACAPELLI",
    format: "1 PEZZO",
    price: 158.0,
  },
  // Lista de productos...
  {
    category: "ANTI-AGE",
    product: "ANTI-AGE C18 100 ml.",
    format: "6 FLACONE",
    price: 39.5,
  },
  {
    category: "ANTI-AGE",
    product: "ANTI-AGE C18 50 ml.",
    format: "6 FLACONE",
    price: 28.0,
  },
  {
    category: "ANTI-AGE",
    product: "DISPLAY ANTI-AGE",
    format: "1 PEZZO",
    price: 16.0,
  },
  {
    category: "ANTI-AGE",
    product: "POSTER ANTI-AGE",
    format: "1 PEZZO",
    price: 1.9,
  },
  {
    category: "ANTI-AGE",
    product: "DEPLIANT ANTI-AGE",
    format: "1 PEZZO",
    price: 2.4,
  },
  // Lista de productos...
  {
    category: "GREEN CARE",
    product: "KIT GREEN CARE",
    format: "1 KIT",
    price: 55.0,
  },
  {
    category: "GREEN CARE",
    product: "SANITIZING TREATMENT NR 1 100ml",
    format: "6 FLACONE",
    price: 96.0,
  },
  {
    category: "GREEN CARE",
    product: "VITAMIN SHAMPOO NR 2 250ml",
    format: "6 FLACONE",
    price: 108.0,
  },
  {
    category: "GREEN CARE",
    product: "VITAMIN LOTION NR 3 100ml",
    format: "6 FLACONE",
    price: 126.0,
  },
  {
    category: "GREEN CARE",
    product: "DEPLIANT GREEN CARE",
    format: "1 PEZZO",
    price: 2.4,
  },
  {
    category: "BIOLOGICAL WAVING SYSTEM",
    product: "BIOLOGICAL WAVING SYSTEM 100 ml",
    format: "1 KIT (PERM+NEUTR)",
    price: 19.5,
  },
  {
    category: "BIOLOGICAL WAVING SYSTEM",
    product: "BROCHURE BWS",
    format: "1 PEZZO",
    price: 2.45,
  },
  {
    category: "BIOLOGICAL WAVING SYSTEM",
    product: "POSTER BWS",
    format: "1 PEZZO",
    price: 1.8,
  },
  {
    category: "IFIX",
    product: "AQUA WAX 100 ml",
    format: "6 VASO",
    price: 15.0,
  },
  {
    category: "IFIX",
    product: "CURLS WAVE 100 ml",
    format: "6 VASO",
    price: 14.8,
  },
  {
    category: "IFIX",
    product: "SHAPE-IT 100 ml",
    format: "6 VASO",
    price: 16.5,
  },
  {
    category: "IFIX",
    product: "FIX IT GEL 200 ml",
    format: "6 TUBO",
    price: 16.0,
  },
  {
    category: "IFIX",
    product: "WET LOOK GEL 200 ml",
    format: "6 TUBO",
    price: 12.0,
  },
  {
    category: "IFIX",
    product: "FORMING LACQUER Strong 300 ml",
    format: "12 BOMBOLA",
    price: 19.5,
  },
  {
    category: "IFIX",
    product: "VOLUMIZING MOUSSE Strong 300 ml",
    format: "12 BOMBOLA",
    price: 16.5,
  },
  {
    category: "IFIX",
    product: "POWER SHINE 500 ml",
    format: "12 BOMBOLA",
    price: 19.0,
  },
  {
    category: "IFIX",
    product: "POWER SHINE 75 ml",
    format: "12 BOMBOLA",
    price: 5.95,
  },
  {
    category: "IFIX",
    product: "FORMING GLAZE 150 ml",
    format: "6 FLACONE",
    price: 13.0,
  },
  {
    category: "IFIX",
    product: "PURE VOLUME 150 ml",
    format: "6 FLACONE",
    price: 14.8,
  },
  {
    category: "IFIX",
    product: "POLISHING SERUM 150 ml",
    format: "6 FLACONE",
    price: 28.0,
  },
  {
    category: "URBN",
    product: "PURIFYING SHAMPOO 1 lt",
    format: "1 lt. 6 FLACONE",
    price: 28.0,
  },
  {
    category: "URBN",
    product: "PURIFYING MASK 1 lt",
    format: "1 lt. 6 FLACONE",
    price: 29.0,
  },
  {
    category: "URBN",
    product: "PURIFYING SHAMPOO 250 ml",
    format: "250 ml. 6 FLACONE",
    price: 13.5,
  },
  {
    category: "URBN",
    product: "PURIFYING MASK 200 ml",
    format: "200 ml. 6 FLACONE",
    price: 14.0,
  },
  {
    category: "URBN",
    product: "NOURISHING MOUSSE 200 ml",
    format: "200 ml. 6 FLACONE",
    price: 21.0,
  },
  {
    category: "URBN",
    product: "NEW URBN WHYTWELVE 150 ml",
    format: "150 ml. 6 FLACONE",
    price: 13.0,
  },
  {
    category: "URBN",
    product: "URBN DISPLAY 1 PEZZO",
    format: "1 PEZZO",
    price: 13.0,
  },
  {
    category: "URBN",
    product: "URBN BANNER 1 PEZZO",
    format: "1 PEZZO",
    price: 25.0,
  },
  {
    category: "URBN",
    product: "URBN POSTER 1 PEZZO",
    format: "1 PEZZO",
    price: 1.8,
  },
  {
    category: "URBN",
    product: "URBN BROCHURE 1 PEZZO",
    format: "1 PEZZO",
    price: 2.4,
  },
  {
    category: "BOTTOX EFFECT LOTION",
    product: "KIT BOTTOX 50 ml",
    format: "1 KIT",
    price: 143.0,
  },
  {
    category: "BOTTOX EFFECT LOTION",
    product: "CLARIFYING SHAMPOO 500 ml.",
    format: "1 PEZZO",
    price: 17.0,
  },
  {
    category: "BOTTOX EFFECT LOTION",
    product: "POSTER BOTTOX 1 PEZZO",
    format: "1 PEZZO",
    price: 1.85,
  },
  {
    category: "BOTTOX EFFECT LOTION",
    product: "DEPLIANT BOTTOX 1 PEZZO",
    format: "1 PEZZO",
    price: 2.35,
  },
  {
    categoria: "KEEP IN COLOR MOISTURIZING",
    producto: "KEEP IN COLOR MOISTURIZING SHAMPOO",
    formato: "1 Lt.",
    precio: "€ 28,00",
  },
  {
    categoria: "KEEP IN COLOR MOISTURIZING",
    producto: "KEEP IN COLOR MOISTURIZING MASK",
    formato: "1 Lt.",
    precio: "€ 34,00",
  },
  {
    categoria: "KEEP IN COLOR MOISTURIZING",
    producto: "KEEP IN COLOR MOISTURIZING SHAMPOO",
    formato: "250 ml",
    precio: "€ 14,80",
  },
  {
    categoria: "KEEP IN COLOR MOISTURIZING",
    producto: "KEEP IN COLOR MOISTURIZING MASK",
    formato: "200 ml",
    precio: "€ 15,00",
  },
  {
    categoria: "KEEP IN COLOR MOISTURIZING",
    producto: "BLISTERS KEEP IN COLOR MOISTURIZING",
    formato: "1 PEZZO",
    precio: "€ 1,20",
  },
  {
    categoria: "KEEP IN COLOR MOISTURIZING",
    producto: "BROCHURE KEEP IN COLOR MOISTURIZING",
    formato: "1 PEZZO",
    precio: "€ 2,40",
  },
  {
    categoria: "KEEP IN COLOR MOISTURIZING",
    producto: "POSTER KEEP IN COLOR MOISTURIZING",
    formato: "1 PEZZO",
    precio: "€ 1,80",
  },
  {
    categoria: "FORFORA-GRASSO",
    producto: "SINERGY WASH",
    formato: "1000 ml",
    precio: "€ 29,50",
  },
  {
    categoria: "FORFORA-GRASSO",
    producto: "SINERGY WASH",
    formato: "250 ml",
    precio: "€ 16,50",
  },
  {
    categoria: "ANTICADUTA",
    producto: "REGAL WASH",
    formato: "1000 ml",
    precio: "€ 25,00",
  },
  {
    categoria: "ANTICADUTA",
    producto: "REGAL WASH",
    formato: "250 ml",
    precio: "€ 13,00",
  },
  {
    categoria: "ANTICADUTA",
    producto: "REGAL WASH",
    formato: "100 ml",
    precio: "€ 6,00",
  },
  {
    categoria: "ANTICADUTA",
    producto: "REGAL LIFE",
    formato: "12 x 6 ml",
    precio: "€ 42,00",
  },
  {
    categoria: "ANTICADUTA",
    producto: "REGAL LIFE",
    formato: "4 x 6 ml",
    precio: "€ 18,00",
  },
  {
    categoria: "RICOSTRUZIONE",
    producto: "HYDRO-KERATIN SHAMPOO",
    formato: "1000 ml",
    precio: "€ 26,00",
  },
  {
    categoria: "RICOSTRUZIONE",
    producto: "MULTI-VITAMIN OIL",
    formato: "500 ml",
    precio: "€ 31,00",
  },
  {
    categoria: "RICOSTRUZIONE",
    producto: "KERABONDING MASK",
    formato: "500 ml",
    precio: "€ 23,00",
  },
  {
    categoria: "RICOSTRUZIONE",
    producto: "HYDRO-KERATIN SHAMPOO",
    formato: "250 ml",
    precio: "€ 13,00",
  },
  {
    categoria: "RICOSTRUZIONE",
    producto: "MULTI-VITAMIN OIL",
    formato: "150 ml",
    precio: "€ 25,00",
  },
  {
    categoria: "RICOSTRUZIONE",
    producto: "KERABONDING MASK",
    formato: "200 ml",
    precio: "€ 14,50",
  },
  {
    categoria: "HAIR COLOR ACCELERATOR",
    producto: "HAIR COLOR ACCELERATOR",
    formato: "1 SC x 4Flaconi",
    precio: "€ 59,00",
  },
  {
    categoria: "UNDEFINED",
    producto: "PEACH SHAMPOO",
    formato: "10 lt. 1 FUSTINO",
    precio: "€ 116,00",
  },
  {
    categoria: "UNDEFINED",
    producto: "LIPOSOME HAIR COLOR con ACQUA TERMALE",
    formato: "100ml. 6 TUBO",
    precio: "€ 11,50",
  },
  {
    categoria: "UNDEFINED",
    producto: "BOTANICAL HAIR COLOR",
    formato: "100ml. 6 TUBO",
    precio: "€ 12,00",
  },
  {
    categoria: "UNDEFINED",
    producto: "VITAMIN COLORS",
    formato: "125ml. 3 FLACONE",
    precio: "€ 21,00",
  },
  {
    categoria: "UNDEFINED",
    producto: "OXICREME 20 - 30 - 40 vol. - Active Lotion",
    formato: "1 lt. 6 FLACONE",
    precio: "€ 12,50",
  },
  {
    categoria: "UNDEFINED",
    producto: "BLEACH POWDER",
    formato: "500 gr. 1 PEZZO",
    precio: "€ 35,00",
  },
  {
    categoria: "UNDEFINED",
    producto: "BLEACH POWDER PLUS",
    formato: "500 gr. 1 PEZZO",
    precio: "€ 36,00",
  },
  {
    categoria: "UNDEFINED",
    producto: "DARK DIAMOND",
    formato: "500 gr. 1 PEZZO",
    precio: "€ 37,00",
  },
];
