export const products = [
  {
    id: 1,
    title: 'Product 1',
    desc: 'lorem ipsum dolor sit amet consectetur adipisicing elit.',
    image: '/products/image-1.jpg',
    newFlag: true,
    price: 979.14,
    discount: 5,
    favorite: true,
    brand: 'Marca 1',
    category: 'Peluqueria',
    subCategory: [''],
    available: true,
  },
  {
    id: 2,
    title: 'Product 2',
    desc: 'Brief description',
    image: '/products/image-2.jpg',
    newFlag: false,
    price: 364.29,
    discount: 10,
    favorite: false,
    brand: 'Marca 1',
    category: 'Peluqueria',
    subCategory: [''],
    available: true,
  },
  {
    id: 3,
    title: 'Product 3',
    desc: 'Brief description',
    image: '/products/image-3.jpg',
    newFlag: false,
    price: 936.77,
    discount: 10,
    favorite: false,
    brand: 'Marca 1',
    category: 'Peluqueria',
    subCategory: [''],
    available: true,
  },
  {
    id: 4,
    title: 'Product 4',
    desc: 'Brief description',
    image: '/products/image-4.jpg',
    newFlag: true,
    price: 196.24,
    discount: 10,
    favorite: true,
    brand: 'Marca 1',
    category: 'Estetica',
    subCategory: [''],
    available: true,
  },
  {
    id: 5,
    title: 'Product 5',
    desc: 'Brief description',
    image: '/products/image-5.jpg',
    newFlag: true,
    price: 651.71,
    discount: 5,
    favorite: true,
    brand: 'Marca 1',
    category: 'Barberia',
    subCategory: [''],
    available: false,
  },
  {
    id: 6,
    title: 'Product 6',
    desc: 'Brief description',
    image: '/products/image-6.jpg',
    newFlag: false,
    price: 106.5,
    discount: 5,
    favorite: true,
    brand: 'Marca 1',
    category: 'Barberia',
    subCategory: [''],
    available: false,
  },
  {
    id: 7,
    title: 'Product 7',
    desc: 'Brief description',
    image: '/products/image-7.jpg',
    newFlag: true,
    price: 263.04,
    discount: 5,
    favorite: false,
    brand: 'Marca 1',
    category: 'Barberia',
    subCategory: [''],
    available: false,
  },
  {
    id: 8,
    title: 'Product 8',
    desc: 'Brief description',
    image: '/products/image-8.jpg',
    newFlag: false,
    price: 385.75,
    discount: 5,
    favorite: true,
    brand: 'Marca 4',
    category: 'Estetica',
    subCategory: [''],
    available: true,
  },
  {
    id: 9,
    title: 'Product 8',
    desc: 'Brief description',
    image: '/products/image-8.jpg',
    newFlag: false,
    price: 385.75,
    discount: 5,
    favorite: true,
    brand: 'Marca 3',
    category: 'Estetica',
    subCategory: [''],
    available: true,
  },
  {
    id: 10,
    title: 'Product 8',
    desc: 'Brief description',
    image: '/products/image-8.jpg',
    newFlag: false,
    price: 385.75,
    discount: 5,
    favorite: true,
    brand: 'Marca 2',
    category: 'Estetica',
    subCategory: [''],
    available: true,
  },
  {
    id: 11,
    title: 'Product 8',
    desc: 'Brief description',
    image: '/products/image-8.jpg',
    newFlag: false,
    price: 385.75,
    discount: 5,
    favorite: true,
    brand: 'Marca 4',
    category: 'Estetica',
    subCategory: [''],
    available: true,
  },
  {
    id: 12,
    title: 'Product 8',
    desc: 'Brief description',
    image: '/products/image-8.jpg',
    newFlag: false,
    price: 385.75,
    discount: 5,
    favorite: true,
    brand: 'Marca 3',
    category: 'Barberia',
    subCategory: [''],
    available: true,
  },
  {
    id: 13,
    title: 'Product 8',
    desc: 'Brief description',
    image: '/products/image-8.jpg',
    newFlag: false,
    price: 385.75,
    discount: 5,
    favorite: true,
    brand: 'Marca 2',
    category: 'Barberia',
    subCategory: [''],
    available: false,
  },
];

export const filters = [
  {
    title: 'Marcas',
    titleBackend: 'brand',
    options: ['Marca 1', 'Marca 2', 'Marca 3', 'Marca 4', 'Marca 5', 'Marca 6'],
  },
  {
    title: 'Categoria',
    titleBackend: 'category',
    options: ['Peluqueria', 'Estetica', 'Barberia', 'Aparatologia'],
  },
  {
    title: 'Disponibilidad',
    titleBackend: 'available',
    options: ['Disponible', 'No disponible'],
  },
];


export const sortOptions = [
  {
    title: 'Menor precio',
    value: 'lowToHigh',
  },
  {
    title: 'Mayor precio',
    value: 'highToLow',
  },
  {
    title: 'A a Z',
    value: 'aToZ',
  },
  {
    title: 'Z a A',
    value: 'zToA',
  },
];
