export const eugenpermaProducts = [
  {
    title: "ATTENTIVE PERM N°0",
    format: "125 ML",
    category: "PERMANENTI",
    price: 10.55,
    description: "DESCRIZIONE FORMATO LISTINO",
  },
  {
    title: "ATTENTIVE PERM N°1",
    format: "125 ML",
    category: "PERMANENTI",
    price: 10.55,
    description: "DESCRIZIONE FORMATO LISTINO",
  },
  {
    title: "ATTENTIVE PERM N°2",
    format: "125 ML",
    category: "PERMANENTI",
    price: 10.55,
    description: "DESCRIZIONE FORMATO LISTINO",
  },
  {
    title: "ATTENTIVE PERM N°3",
    format: "125 ML",
    category: "PERMANENTI",
    price: 10.55,
    description: "DESCRIZIONE FORMATO LISTINO",
  },
  {
    title: "NEUTRALIZZANTE UNIVERSALE",
    format: "1000 ML",
    category: "PERMANENTI",
    price: 25.05,
    description: "DESCRIZIONE FORMATO LISTINO",
  },
  {
    title: "LISSIT CONCEPT CREMA STIRANTE",
    format: "200 ML",
    category: "STIRATURA",
    price: 27.32,
    description: "DESCRIZIONE FORMATO LISTINO",
  },
  {
    title: "LISSIT CONCEPT CREMA TRATTANTE",
    format: "200 ML",
    category: "STIRATURA",
    price: 27.32,
    description: "DESCRIZIONE FORMATO LISTINO",
  },
  {
    title: "LISSIT CONCEPT NEUTRALIZZANTE",
    format: "1000 ML",
    category: "STIRATURA",
    price: 24.64,
    description: "DESCRIZIONE FORMATO LISTINO",
  },
  {
    title: "CARMEN 1:1",
    format: "60 ML",
    category: "COLORAZIONE PERMANENTE",
    price: 9.6,
    description: "DESCRIZIONE FORMATO LISTINO",
  },
  {
    title: "CARMEN ATOMIC 1:1 ORANGE/RED/MAGENTA",
    format: "60 ML",
    category: "COLORAZIONE PERMANENTE",
    price: 14.9,
    description: "DESCRIZIONE FORMATO LISTINO",
  },
  {
    title: "COLOR CREME 1:3",
    format: "60 ML",
    category: "COLORAZIONE PERMANENTE",
    price: 13.5,
    description: "DESCRIZIONE FORMATO LISTINO",
  },
  {
    title: "OXYCREM 5-10-20-30-40 VOL. 1000 ML",
    price: 14.67,
    category: "COLORAZIONE PERMANENTE",
    description: "DESCRIZIONE FORMATO LISTINO",
  },
  {
    title: "CARMEN TT 1:2",
    format: "60 ML",
    category: "COLORAZIONE SEMI-PERMANENTE",
    price: 9.6,
    description: "DESCRIZIONE FORMATO LISTINO",
  },
  {
    title: "CARMEN MEN",
    format: "60 ML",
    category: "COLORAZIONE SEMI-PERMANENTE",
    price: 9.6,
    description: "DESCRIZIONE FORMATO LISTINO",
  },
  {
    title: "CARMEN TT DEVELOPER 5-9-15 VOL 1000 ML",
    price: 12.67,
    category: "COLORAZIONE SEMI-PERMANENTE",
    description: "DESCRIZIONE FORMATO LISTINO",
  },
  {
    title: "CARMEN TT SHAMPOO POST-COLORAZIONE",
    format: "1000 ML",
    category: "COLORAZIONE SEMI-PERMANENTE",
    price: 18.6,
    description: "DESCRIZIONE FORMATO LISTINO",
  },
  {
    title: "CARMEN RITUEL 1:1",
    format: "60 ML",
    category: "COLORAZIONE NATURALE",
    price: 12.85,
    description: "DESCRIZIONE FORMATO LISTINO",
  },
  {
    title: "CARMEN RITUEL SHAMPOO DETERGENTE JELLY",
    format: "1000 ML",
    category: "COLORAZIONE NATURALE",
    price: 27.17,
    description: "DESCRIZIONE FORMATO LISTINO",
  },
  {
    title: "CARMEN RITUEL BALSAMO",
    format: "500 ML",
    category: "COLORAZIONE NATURALE",
    price: 25.04,
    description: "DESCRIZIONE FORMATO LISTINO",
  },
  {
    title: "OSSIGENO ACTIVATING CREAM 5-9-20-30 VOL. 1000 ML",
    price: 24.19,
    category: "COLORAZIONE NATURALE",
    description: "DESCRIZIONE FORMATO LISTINO",
  },
  {
    title: "BLUSH SATINE",
    format: "100 ML",
    category: "COLORAZIONE DIRETTA",
    price: 15.8,
    description: "DESCRIZIONE FORMATO LISTINO",
  },
  {
    title: "BLUSH FLASHY MIX",
    format: "100 ML",
    category: "COLORAZIONE DIRETTA",
    price: 20.25,
    description: "DESCRIZIONE FORMATO LISTINO",
  },
  {
    title: "BLUSH CARE RADIANCE ENHANCING BRIGHTENING FOAM",
    format: "200 ML",
    category: "COLORAZIONE DIRETTA",
    price: 14.24,
    description: "DESCRIZIONE FORMATO LISTINO",
  },
  {
    title: "POUDR 9 - SCHIARENTE SUPER INTENSO",
    format: "450 GR",
    category: "DECOLORAZIONE",
    price: 44.76,
    description: "DESCRIZIONE FORMATO LISTINO",
  },
  {
    title: "POUDR 7 - COMPATTA",
    format: "450 GR",
    category: "DECOLORAZIONE",
    price: 43.27,
    description: "DESCRIZIONE FORMATO LISTINO",
  },
  {
    title: "POUDR 0% - POLVERE SENZA AMMONIACA",
    format: "450 GR",
    category: "DECOLORAZIONE",
    price: 49.7,
    description: "DESCRIZIONE FORMATO LISTINO",
  },
  {
    title: "POUDR 6 - AIR LIBRE",
    format: "450 GR",
    category: "DECOLORAZIONE",
    price: 43.27,
    description: "DESCRIZIONE FORMATO LISTINO",
  },
  {
    title: "PAT7 - DECOLORANTE IN PASTA",
    format: "250 GR",
    category: "DECOLORAZIONE",
    price: 34.18,
    description: "DESCRIZIONE FORMATO LISTINO",
  },
  {
    title: "HUIL 4 - OLIO SCHIARENTE",
    format: "500 ML",
    category: "DECOLORAZIONE",
    price: 40.0,
    description: "DESCRIZIONE FORMATO LISTINO",
  },
  {
    title: "LATTE NEUTRALIZZANTE POST DECOLORAZIONE",
    format: "500 ML",
    category: "DECOLORAZIONE",
    price: 28.0,
    description: "DESCRIZIONE FORMATO LISTINO",
  },
  {
    title: "DEMAK - RIMUOVI DECOLORAZIONE 12 x 25 GR",
    price: 59.09,
    category: "DECOLORAZIONE",
    description: "DESCRIZIONE FORMATO LISTINO",
  },
  {
    title: "DECOLORAZIONE TONER T 02-12-23-00 60 ML",
    price: 14.63,
    category: "DECOLORAZIONE",
    description: "DESCRIZIONE FORMATO LISTINO",
  },
  {
    title: "SHAMPOO 250 ML",
    price: 11.25,
    category: "DECOLORAZIONE",
    description: "DESCRIZIONE FORMATO LISTINO",
  },
  {
    title: "SPRAY COCCO PROTETTIVO 200 ML",
    price: 17.09,
    category: "DECOLORAZIONE",
    description: "DESCRIZIONE FORMATO LISTINO",
  },
  {
    title: "ANTI-GIALLO - BIONDO POLARE 200 ML",
    price: 19.0,
    category: "DECOLORAZIONE",
    description: "DESCRIZIONE FORMATO LISTINO",
  },
  {
    title: "SCHIARENTE - BIONDO DORATO 200 ML",
    price: 19.0,
    category: "DECOLORAZIONE",
    description: "DESCRIZIONE FORMATO LISTINO",
  },
  {
    title: "NEUTRALIZZANTE - BIONDO BEIGE 200 ML",
    price: 19.0,
    category: "DECOLORAZIONE",
    description: "DESCRIZIONE FORMATO LISTINO",
  },
  // Lista de productos...
  {
    title: "EQUIVITAL BASE LAVANTE CONCENTRATA",
    category: "COMPLEMENTI TECNICI",
    format: "5000 ML",
    price: 99.0,
  },
  {
    title: "EQUIVITAL SHAMPOO POST-COLORAZIONE",
    category: "COMPLEMENTI TECNICI",
    format: "1000 ML",
    price: 23.75,
  },
  {
    title: "EQUIVITAL TRATTAMENTO POST-COLORAZIONE",
    category: "COMPLEMENTI TECNICI",
    format: "1000 ML",
    price: 51.1,
  },
  {
    title: "EQUIVITAL SMACCHIATORE",
    category: "COMPLEMENTI TECNICI",
    format: "250 ML",
    price: 11.4,
  },
  {
    title: "EQUIVITAL CREMA BARRIERA",
    category: "COMPLEMENTI TECNICI",
    format: "100 ML",
    price: 14.05,
  },
  {
    title: "EQUIVITAL SHAMPOO PRE-PERMANENTE",
    category: "COMPLEMENTI TECNICI",
    format: "1000 ML",
    price: 42.1,
  },
  {
    title: "CURL CREAM",
    category: "COMPLEMENTI TECNICI",
    format: "50 mL",
    price: 9.75,
  },
  {
    title: "CURL CREAM",
    category: "COMPLEMENTI TECNICI",
    format: "150 mL",
    price: 14.55,
  },
  {
    title: "CURL MOUSSE",
    category: "COMPLEMENTI TECNICI",
    format: "200 mL",
    price: 14.55,
  },
  {
    title: "CURL SPRAY",
    category: "COMPLEMENTI TECNICI",
    format: "200 mL",
    price: 18.0,
  },
  {
    title: "VOLUME MOUSSE",
    category: "COMPLEMENTI TECNICI",
    format: "200 mL",
    price: 14.55,
  },
  {
    title: "VOLUME SPRAY",
    category: "COMPLEMENTI TECNICI",
    format: "200 mL",
    price: 16.15,
  },
  {
    title: "LISS'HEAT SPRAY",
    category: "COMPLEMENTI TECNICI",
    format: "200 mL",
    price: 16.15,
  },
  {
    title: "SPRAY GLOSS",
    category: "COMPLEMENTI TECNICI",
    format: "200 mL",
    price: 16.15,
  },
  {
    title: "TEXTURE PASTE",
    category: "COMPLEMENTI TECNICI",
    format: "150 mL",
    price: 14.55,
  },
  {
    title: "MOLDING WAX",
    category: "COMPLEMENTI TECNICI",
    format: "75 gr",
    price: 15.2,
  },
  {
    title: "FLEXI BALM",
    category: "COMPLEMENTI TECNICI",
    format: "125 gr",
    price: 15.2,
  },
  {
    title: "FIXER GUM",
    category: "COMPLEMENTI TECNICI",
    format: "75 gr",
    price: 18.0,
  },
  {
    title: "XTRA STRONG SPRAY",
    category: "COMPLEMENTI TECNICI",
    format: "200 mL",
    price: 16.6,
  },
  {
    title: "FIXING MOUSSE",
    category: "COMPLEMENTI TECNICI",
    format: "200 mL",
    price: 14.55,
  },
  {
    title: "HAIRSCULPTING SPRAY",
    category: "COMPLEMENTI TECNICI",
    format: "200 mL",
    price: 15.2,
  },
  {
    title: "HAIRSCULPTING SPRAY",
    category: "COMPLEMENTI TECNICI",
    format: "1000 mL",
    price: 44.4,
  },
  {
    title: "MODELING SPRAY",
    category: "COMPLEMENTI TECNICI",
    format: "300 mL",
    price: 17.5,
  },
  {
    title: "MODELING SPRAY",
    category: "COMPLEMENTI TECNICI",
    format: "500 mL",
    price: 24.6,
  },
  {
    title: "XTRA STRONG GEL",
    category: "COMPLEMENTI TECNICI",
    format: "150 mL",
    price: 18.0,
  },
  {
    title: "FINISHING SPRAY - IN ARRIVO",
    category: "COMPLEMENTI TECNICI",
    format: "75 mL",
    price: 10.65,
  },
  {
    title: "FINISHING SPRAY",
    category: "COMPLEMENTI TECNICI",
    format: "300 mL",
    price: 17.5,
  },
  {
    title: "FINISHING SPRAY",
    category: "COMPLEMENTI TECNICI",
    format: "500 mL",
    price: 24.6,
  },
  {
    title: "SHAMPOO NUTRIZIONE",
    category: "NUTRIZIONE",
    format: "100 ML",
    price: 12.7,
  },
  {
    title: "SHAMPOO NUTRIZIONE",
    category: "NUTRIZIONE",
    format: "300 ML",
    price: 15.4,
  },
  {
    title: "SHAMPOO NUTRIZIONE",
    category: "NUTRIZIONE",
    format: "1000 ML",
    price: 38.9,
  },
  {
    title: "MASK NUTRIZIONE",
    category: "NUTRIZIONE",
    format: "75 ML",
    price: 12.1,
  },
  {
    title: "MASK NUTRIZIONE",
    category: "NUTRIZIONE",
    format: "250 ML",
    price: 23.45,
  },
  {
    title: "MASK NUTRIZIONE",
    category: "NUTRIZIONE",
    format: "500 ML",
    price: 45.05,
  },
  {
    title: "SHAMPOO USO FREQUENTE",
    category: "USO FREQUENTE - IDRATAZIONE",
    format: "300 ML",
    price: 15.4,
  },
  {
    title: "SHAMPOO USO FREQUENTE",
    category: "USO FREQUENTE - IDRATAZIONE",
    format: "1000 ML",
    price: 38.9,
  },
  {
    title: "MASK USO FREQUENTE",
    category: "USO FREQUENTE - IDRATAZIONE",
    format: "75 ML",
    price: 12.1,
  },
  {
    title: "MASK USO FREQUENTE",
    category: "USO FREQUENTE - IDRATAZIONE",
    format: "250 ML",
    price: 23.45,
  },
  {
    title: "MASK USO FREQUENTE",
    category: "USO FREQUENTE - IDRATAZIONE",
    format: "500 ML",
    price: 45.05,
  },
  {
    title: "SPRAY USO FREQUENTE PROTETTIVO",
    category: "USO FREQUENTE - IDRATAZIONE",
    format: "200 ML",
    price: 21.8,
  },
  // Lista de productos...
  {
    title: "TRATTAMENTO VOLUME",
    category: "VOLUME",
    format: "12 x 6 ML",
    price: 59.65,
  },
  {
    title: "SHAMPOO VOLUME",
    category: "VOLUME",
    format: "300 ML",
    price: 15.4,
  },
  {
    title: "SHAMPOO VOLUME",
    category: "VOLUME",
    format: "1000 ML",
    price: 38.9,
  },
  {
    title: "VOLUME SPRAY",
    category: "VOLUME",
    format: "200 ML",
    price: 21.8,
  },
  {
    title: "SHAMPOO COLOR",
    category: "COLORE",
    format: "100 ML",
    price: 12.7,
  },
  {
    title: "SHAMPOO COLOR",
    category: "COLORE",
    format: "300 ML",
    price: 15.4,
  },
  {
    title: "SHAMPOO COLOR",
    category: "COLORE",
    format: "1000 ML",
    price: 38.9,
  },
  {
    title: "MASK COLOR",
    category: "COLORE",
    format: "75 ML",
    price: 12.1,
  },
  {
    title: "MASK COLOR",
    category: "COLORE",
    format: "250 ML",
    price: 23.45,
  },
  {
    title: "COLOR MASK",
    category: "COLORE",
    format: "500 ML",
    price: 45.05,
  },
  {
    title: "COLOR CARE SPRAY",
    category: "COLORE",
    format: "200 ML",
    price: 21.8,
  },
  {
    title: "SHAMPOO SILVER",
    category: "SILVER",
    format: "300 ML",
    price: 15.4,
  },
  {
    title: "SHAMPOO SILVER",
    category: "SILVER",
    format: "1000 ML",
    price: 38.9,
  },
  {
    title: "SHAMPOO ANTI-FORFORA",
    category: "ANTI FORFORA",
    format: "300 ML",
    price: 15.4,
  },
  {
    title: "SHAMPOO ANTI-FORFORA",
    category: "ANTI FORFORA",
    format: "1000 ML",
    price: 38.9,
  },
  {
    title: "LACCA TENUTA NORMALE",
    category: "STYLING",
    format: "300 ML",
    price: 17.35,
  },
  {
    title: "LACCA TENUTA NORMALE",
    category: "STYLING",
    format: "500 ML",
    price: 19.65,
  },
  {
    title: "LACCA TENUTA FORTE",
    category: "STYLING",
    format: "300 ML",
    price: 17.35,
  },
  {
    title: "LACCA TENUTA FORTE",
    category: "STYLING",
    format: "500 ML",
    price: 19.65,
  },
  {
    title: "SUPER DETANGLING SHAMPOO",
    category: "SUPER DISTRICANTE",
    format: "300 ML",
    price: 17.6,
  },
  {
    title: "SUPER DETANGLING SPRAY",
    category: "SUPER DISTRICANTE",
    format: "125 ML",
    price: 17.2,
  },
  {
    title: "SHAMPOO PURIFICANTE",
    category: "PURIFICANTE",
    format: "300 ML",
    price: 15.4,
  },
  {
    title: "SHAMPOO PURIFICANTE",
    category: "PURIFICANTE",
    format: "1000 ML",
    price: 38.9,
  },
  {
    title: "BARRETTA SHAMPOO PURIFICANTE",
    category: "SHAMPOO SOLIDO",
    format: "85 GR",
    price: 10.35,
  },
  {
    title: "BARRETTA SHAMPOO ADDOLCENTE",
    category: "SHAMPOO SOLIDO",
    format: "85 GR",
    price: 10.35,
  },
  {
    title: "ESSENTIEL KERATIN GOLD SHAMPOO",
    category: "GOLD CAPELLI FRAGILI",
    format: "100 ML",
    price: 11.8,
  },
  {
    title: "ESSENTIEL KERATIN GOLD SHAMPOO",
    category: "GOLD CAPELLI FRAGILI",
    format: "250 ML",
    price: 15.25,
  },
  {
    title: "ESSENTIEL KERATIN GOLD SHAMPOO",
    category: "GOLD CAPELLI FRAGILI",
    format: "1000 ML",
    price: 42.25,
  },
  {
    title: "ESSENTIEL KERATIN GOLD MASK",
    category: "GOLD CAPELLI FRAGILI",
    format: "50 ML",
    price: 10.2,
  },
  {
    title: "ESSENTIEL KERATIN GOLD MASK",
    category: "GOLD CAPELLI FRAGILI",
    format: "150 ML",
    price: 22.65,
  },
  {
    title: "ESSENTIEL KERATIN GOLD MASK",
    category: "GOLD CAPELLI FRAGILI",
    format: "500 ML",
    price: 49.95,
  },
  {
    title: "ESSENTIEL KERATIN GOLD TRATTAMENTO BOOSTER",
    category: "GOLD CAPELLI FRAGILI",
    format: "10 X 10 ML",
    price: 57.65,
  },
  {
    title: "ESSENTIEL KERATIN GLOW SHAMPOO",
    category: "GLOW TUTTI I CAPELLI",
    format: "250 ML",
    price: 15.25,
  },
  {
    title: "ESSENTIEL KERATIN GLOW SHAMPOO",
    category: "GLOW TUTTI I CAPELLI",
    format: "1000 ML",
    price: 42.25,
  },
  {
    title: "ESSENTIEL KERATIN GLOW MASK",
    category: "GLOW TUTTI I CAPELLI",
    format: "150 ML",
    price: 22.65,
  },
  {
    title: "ESSENTIEL KERATIN GLOW MASK",
    category: "GLOW TUTTI I CAPELLI",
    format: "500 ML",
    price: 49.95,
  },
  {
    title: "ESSENTIEL SERUM LEAVE-IN",
    category: "GLOW TUTTI I CAPELLI",
    format: "50 ML",
    price: 35.6,
  },
  {
    title: "ESSENTIEL KERATIN PULP CONDITIONNER PRE LAVAGGIO",
    category: "PULP CAPELLI FINI",
    format: "200 ML",
    price: 22.85,
  },
  {
    title: "ESSENTIEL KERATIN PULP SHAMPOO",
    category: "PULP CAPELLI FINI",
    format: "250 ML",
    price: 15.25,
  },
  {
    title: "ESSENTIEL KERATIN PULP SHAMPOO",
    category: "PULP CAPELLI FINI",
    format: "1000 ML",
    price: 42.25,
  },
  {
    title: "ESSENTIEL KERATIN FRIZZ 2 IN 1 CARE SHAMPOO",
    category: "FRIZZ CAPELLI RICCI",
    format: "400 ML",
    price: 30.75,
  },
  {
    title: "ESSENTIEL KERATIN FRIZZ 2 IN 1 CARE SHAMPOO",
    category: "FRIZZ CAPELLI RICCI",
    format: "1000 ML",
    price: 42.25,
  },
  {
    title: "ESSENTIEL KERATIN FRIZZ EXPRESS OLIO",
    category: "FRIZZ CAPELLI RICCI",
    format: "200 ML",
    price: 22.3,
  },
  {
    title: "ESSENTIEL KERATIN NUTRI SHAMPOO",
    category: "NUTRI CAPELLI SECCHI",
    format: "250 ML",
    price: 15.25,
  },
  {
    title: "ESSENTIEL KERATIN NUTRI SHAMPOO",
    category: "NUTRI CAPELLI SECCHI",
    format: "1000 ML",
    price: 42.25,
  },
  {
    title: "ESSENTIEL KERATIN NUTRI MASK",
    category: "NUTRI CAPELLI SECCHI",
    format: "150 ML",
    price: 22.65,
  },
  {
    title: "ESSENTIEL KERATIN NUTRI MASK",
    category: "NUTRI CAPELLI SECCHI",
    format: "500 ML",
    price: 49.95,
  },
  {
    title: "ESSENTIEL KERATIN NUTRI SERUM",
    category: "NUTRI CAPELLI SECCHI",
    format: "200 ML",
    price: 39.2,
  },
  {
    title: "ESSENTIEL NUTRITION OLIO",
    category: "NUTRI CAPELLI SECCHI",
    format: "100 ML",
    price: 35.6,
  },
  {
    title: "ESSENTIEL KERATIN COLOR SHAMPOO",
    category: "COLOR CAPELLI COLORATI",
    format: "100 ML",
    price: 11.8,
  },
  {
    title: "ESSENTIEL KERATIN COLOR SHAMPOO",
    category: "COLOR CAPELLI COLORATI",
    format: "250 ML",
    price: 15.25,
  },
  {
    title: "ESSENTIEL KERATIN COLOR SHAMPOO",
    category: "COLOR CAPELLI COLORATI",
    format: "1000 ML",
    price: 42.25,
  },
  {
    title: "ESSENTIEL KERATIN COLOR MASK",
    category: "COLOR CAPELLI COLORATI",
    format: "50 ML",
    price: 10.2,
  },
  {
    title: "ESSENTIEL KERATIN COLOR MASK",
    category: "COLOR CAPELLI COLORATI",
    format: "150 ML",
    price: 22.65,
  },
  {
    title: "ESSENTIEL KERATIN COLOR MASK",
    category: "COLOR CAPELLI COLORATI",
    format: "500 ML",
    price: 49.95,
  },
  {
    title: "ESSENTIEL KERATIN COLOR SPRAY BI-FASE",
    category: "COLOR CAPELLI COLORATI",
    format: "200 ML",
    price: 23.05,
  },
  {
    title: "ESSENTIEL KERATIN SILVER SHAMPOO",
    category: "SILVER CAPELLI BIONDI-DEC-BIANCHI",
    format: "250 ML",
    price: 15.25,
  },
  {
    title: "ESSENTIEL KERATIN SILVER SHAMPOO",
    category: "SILVER CAPELLI BIONDI-DEC-BIANCHI",
    format: "1000 ML",
    price: 42.25,
  },
  {
    title: "ESSENTIEL KERATIN FORCE SHAMPOO",
    category: "FORCE CADUTA DEI CAPELLI",
    format: "250 ML",
    price: 15.25,
  },
  {
    title: "ESSENTIEL KERATIN FORCE SHAMPOO",
    category: "FORCE CADUTA DEI CAPELLI",
    format: "1000 ML",
    price: 42.25,
  },
  {
    title: "ESSENTIEL KERATIN FORCE FIALE",
    category: "FORCE CADUTA DEI CAPELLI",
    format: "12 x 3,5 ML",
    price: 67.05,
  },
  {
    title: "ESSENTIEL KERATIN FORCE SPRAY",
    category: "FORCE CADUTA DEI CAPELLI",
    format: "200 ML",
    price: 41.45,
  },
  {
    title: "ESSENTIEL KERATIN SENSITIVE SHAMPOO",
    category: "SENSITIVE CUTE SENSIBILE",
    format: "250 ML",
    price: 15.25,
  },
  {
    title: "ESSENTIEL KERATIN SENSITIVE SHAMPOO",
    category: "SENSITIVE CUTE SENSIBILE",
    format: "1000 ML",
    price: 42.25,
  },
  {
    title: "ESSENTIEL KERATIN SENSITIVE SIERO",
    category: "SENSITIVE CUTE SENSIBILE",
    format: "40 ML",
    price: 25.65,
  },
  {
    title: "ESSENTIEL SHAMPOO KERATIN BALANCE",
    category: "BALANCE CAPELLI GRASSO E FORFORA",
    format: "250 ML",
    price: 15.25,
  },
  {
    title: "ESSENTIEL SHAMPOO KERATIN BALANCE",
    category: "BALANCE CAPELLI GRASSO E FORFORA",
    format: "1000 ML",
    price: 42.25,
  },
  {
    title: "ESSENTIEL CONDITIONER KERATIN BALANCE",
    category: "BALANCE CAPELLI GRASSO E FORFORA",
    format: "200 ML",
    price: 22.8,
  },
  {
    title: "ESSENTIEL ARGILLA LAVANTE KERATIN BALANCE",
    category: "BALANCE CAPELLI GRASSO E FORFORA",
    format: "250 ML",
    price: 19.6,
  },
  {
    title: "ESSENTIEL KERATIN SUN SHAMPOO",
    category: "SUN",
    format: "250 ML",
    price: 15.25,
  },
  {
    title: "ESSENTIEL KERATIN SUN 2-IN-1 MASK",
    category: "SUN",
    format: "150 ML",
    price: 21.2,
  },
  {
    title: "ESSENTIEL PROTECTION MIST - IN ARRIVO -",
    category: "SUN",
    format: "150 ML",
    price: 21.2,
  },
];
