export const products = [
  {
    id: 1,
    title: "OLIO DI ARGAN",
    format: "125 ML",
    category: "Capelli",
    price: 10.55,
    brand: "She",
    brandLogo: "/logoShe.png",
    subCategory: "Olio",
    newFlag: true,
    favorite: true,
    bestseller: true,
    image: "/products/olioArgan.png",
    region: ["Abruzzo", "Lazio"],
  },
  {
    id: 2,
    title: "ATTENTIVE PERM N°1",
    format: "125 ML",
    category: "Capelli",
    price: 10.55,
    brand: "Chenice",
    brandLogo: "/logoChenice.png",
    subCategory: ["ALTRO"],
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-2.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    id: 3,
    title: "ATTENTIVE PERM N°2",
    format: "125 ML",
    category: "Capelli",
    price: 10.55,
    brand: "Eugeneperma",
    brandLogo: "/logoEugeneperma.png",
    subCategory: ["ALTRO"],
    newFlag: true,
    favorite: true,
    bestseller: true,
    image: "/products/olioArgan.png",
    region: ["Abruzzo", "Lazio"],
  },
  {
    id: 4,
    title: "ATTENTIVE PERM N°3",
    format: "125 ML",
    category: "Capelli",
    price: 10.55,
    brand: "Eugeneperma",
    brandLogo: "/logoEugeneperma.png",
    subCategory: ["ALTRO"],
    newFlag: true,
    favorite: true,
    bestseller: true,
    image: "/products/image-2.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    id: 5,
    title: "NEUTRALIZZANTE UNIVERSALE",
    format: "1000 ML",
    category: "Capelli",
    price: 25.05,
    brand: "Eugeneperma",
    brandLogo: "/logoEugeneperma.png",
    subCategory: ["ALTRO"],
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-1.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    id: 6,
    title: "CREMA STIRANTE",
    format: "200 ML",
    category: "Capelli",
    price: 27.32,
    brand: "Eugeneperma",
    brandLogo: "/logoEugeneperma.png",
    subCategory: "Stiratura",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-1.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    id: 7,
    title: "CREMA TRATTANTE",
    format: "200 ML",
    category: "Capelli",
    price: 27.32,
    brand: "Eugeneperma",
    brandLogo: "/logoEugeneperma.png",
    subCategory: "Stiratura",
    newFlag: true,
    favorite: true,
    bestseller: true,
    image: "/products/image-1.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    id: 8,
    title: "NEUTRALIZZANTE",
    format: "1000 ML",
    category: "Cosmetici",
    price: 24.64,
    brand: "Eugeneperma",
    brandLogo: "/logoEugeneperma.png",
    subCategory: "Stiratura",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/olioArgan.png",
    region: ["Abruzzo", "Lazio"],
  },
  {
    id: 9,
    title: "CARMEN 1:1",
    format: "60 ML",
    category: "Capelli",
    price: 9.6,
    brand: "Eugeneperma",
    brandLogo: "/logoEugeneperma.png",
    subCategory: "Permanente",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-1.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    id: 10,
    title: "CARMEN ATOMIC 1:1 ORANGE/RED/MAGENTA",
    format: "60 ML",
    category: "Capelli",
    price: 14.9,
    brand: "Eugeneperma",
    brandLogo: "/logoEugeneperma.png",
    subsubCategory: "Permanente",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-1.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    id: 11,
    title: "COLOR CREME 1:3",
    format: "60 ML",
    subCategory: "Permanente",
    price: 13.5,
    brand: "Eugeneperma",
    brandLogo: "/logoEugeneperma.png",
    category: "Capelli",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-1.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    id: 12,
    title: "OXYCREM 5-10-20-30-40 VOL.",
    format: "1000 ML",
    subCategory: "Permanente",
    price: 14.67,
    brand: "Eugeneperma",
    brandLogo: "/logoEugeneperma.png",
    category: "Capelli",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-1.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    id: 13,
    title: "CARMEN TT 1:2",
    format: "60 ML",
    subCategory: "Semi-Permanente",
    price: 9.6,
    brand: "Eugeneperma",
    brandLogo: "/logoEugeneperma.png",
    category: "Capelli",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-1.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    id: 14,
    title: "CARMEN MEN",
    format: "60 ML",
    subCategory: "Semi-Permanente",
    price: 9.6,
    brand: "Eugeneperma",
    brandLogo: "/logoEugeneperma.png",
    category: "Capelli",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-1.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    id: 15,
    title: "CARMEN TT DEVELOPER 5-9-15 VOL",
    format: "1000 ML",
    price: 12.67,
    subCategory: "Semi-Permanente",
    brand: "Eugeneperma",
    brandLogo: "/logoEugeneperma.png",
    category: "Capelli",
    newFlag: true,
    favorite: true,
    bestseller: true,
    image: "/products/image-1.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    id: 16,
    title: "CARMEN TT SHAMPOO POST-COLORAZIONE",
    format: "1000 ML",
    subCategory: "Semi-Permanente",
    price: 18.6,
    brand: "Eugeneperma",
    brandLogo: "/logoEugeneperma.png",
    category: "Capelli",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-1.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    id: 17,
    title: "CARMEN RITUEL 1:1",
    format: "60 ML",
    subCategory: "Naturale",
    price: 12.85,
    brand: "Eugeneperma",
    brandLogo: "/logoEugeneperma.png",
    category: "Capelli",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-1.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    id: 18,
    title: "CARMEN RITUEL SHAMPOO DETERGENTE JELLY",
    format: "1000 ML",
    subCategory: "Naturale",
    price: 27.17,
    brand: "Eugeneperma",
    brandLogo: "/logoEugeneperma.png",
    category: "Capelli",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-1.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    id: 19,
    title: "CARMEN RITUEL BALSAMO",
    format: "500 ML",
    subCategory: "Naturale",
    price: 25.04,
    brand: "Eugeneperma",
    brandLogo: "/logoEugeneperma.png",
    category: "Capelli",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-1.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    id: 20,
    title: "OSSIGENO ACTIVATING CREAM 5-9-20-30 VOL.",
    format: "1000 ML",
    subCategory: "Naturale",
    price: 24.19,
    brand: "Eugeneperma",
    brandLogo: "/logoEugeneperma.png",
    category: "Capelli",
    newFlag: true,
    favorite: true,
    bestseller: true,
    image: "/products/image-1.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    id: 21,
    title: "BLUSH SATINE",
    format: "100 ML",
    subCategory: "Diretta",
    price: 15.8,
    brand: "Eugeneperma",
    brandLogo: "/logoEugeneperma.png",
    category: "Capelli",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-1.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    id: 22,
    title: "BLUSH FLASHY MIX",
    format: "100 ML",
    subCategory: "Diretta",
    price: 20.25,
    brand: "Eugeneperma",
    brandLogo: "/logoEugeneperma.png",
    category: "Capelli",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-1.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    id: 23,
    title: "BLUSH CARE RADIANCE ENHANCING BRIGHTENING FOAM",
    format: "200 ML",
    subCategory: "Diretta",
    price: 14.24,
    brand: "Eugeneperma",
    brandLogo: "/logoEugeneperma.png",
    category: "Capelli",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-1.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    id: 24,
    title: "POUDR 9 - SCHIARENTE SUPER INTENSO",
    format: "450 GR",
    subCategory: "Decolorazione",
    price: 44.76,
    brand: "Eugeneperma",
    brandLogo: "/logoEugeneperma.png",
    category: "Capelli",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-1.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    id: 25,
    title: "POUDR 7 - COMPATTA",
    format: "450 GR",
    subCategory: "Decolorazione",
    price: 43.27,
    brand: "Eugeneperma",
    brandLogo: "/logoEugeneperma.png",
    category: "Capelli",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-1.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    id: 26,
    title: "POUDR 0% - POLVERE SENZA AMMONIACA",
    format: "450 GR",
    subCategory: "Decolorazione",
    price: 49.7,
    brand: "Eugeneperma",
    brandLogo: "/logoEugeneperma.png",
    category: "Capelli",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-1.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    id: 27,
    title: "POUDR 6 - AIR LIBRE",
    format: "450 GR",
    subCategory: "Decolorazione",
    price: 43.27,
    brand: "Eugeneperma",
    brandLogo: "/logoEugeneperma.png",
    category: "Capelli",
    newFlag: true,
    favorite: true,
    bestseller: true,
    image: "/products/image-1.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    id: 28,
    title: "PAT7 - DECOLORANTE IN PASTA",
    format: "250 GR",
    subCategory: "Decolorazione",
    price: 34.18,
    brand: "Eugeneperma",
    brandLogo: "/logoEugeneperma.png",
    category: "Capelli",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-1.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    id: 29,
    title: "HUIL 4 - OLIO SCHIARENTE",
    format: "500 ML",
    subCategory: "Decolorazione",
    price: 40.0,
    brand: "Eugeneperma",
    brandLogo: "/logoEugeneperma.png",
    category: "Capelli",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-1.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    id: 30,
    title: "LATTE NEUTRALIZZANTE POST Decolorazione",
    format: "500 ML",
    subCategory: "Decolorazione",
    price: 28.0,
    brand: "Eugeneperma",
    brandLogo: "/logoEugeneperma.png",
    category: "Capelli",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-1.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    id: 31,
    title: "RIMUOVI Decolorazione",
    format: "12 x 25 GR",
    subCategory: "Decolorazione",
    price: 59.09,
    brand: "Eugeneperma",
    brandLogo: "/logoEugeneperma.png",
    category: "Capelli",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-1.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    id: 32,
    title: "Decolorazione TONER T 02-12-23-00",
    format: "60 ML",
    subCategory: "Decolorazione",
    price: 14.63,
    brand: "Eugeneperma",
    brandLogo: "/logoEugeneperma.png",
    category: "Capelli",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-1.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    id: 33,
    format: "250 ML",
    title: "SHAMPOO",
    subCategory: "Decolorazione",
    price: 11.25,
    brand: "Eugeneperma",
    brandLogo: "/logoEugeneperma.png",
    category: "Capelli",
    newFlag: true,
    favorite: true,
    bestseller: true,
    image: "/products/image-1.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    id: 34,
    title: "SPRAY COCCO PROTETTIVO",
    format: "200 ML",
    subCategory: "Decolorazione",
    price: 17.09,
    brand: "Eugeneperma",
    brandLogo: "/logoEugeneperma.png",
    category: "Capelli",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-1.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    id: 35,
    title: "ANTI-GIALLO - BIONDO POLARE",
    format: "200 ML",
    subCategory: "Decolorazione",
    price: 19.0,
    brand: "Eugeneperma",
    brandLogo: "/logoEugeneperma.png",
    category: "Capelli",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-1.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    id: 36,
    title: "SCHIARENTE - BIONDO DORATO",
    format: "200 ML",
    subCategory: "Decolorazione",
    price: 19.0,
    brand: "Eugeneperma",
    brandLogo: "/logoEugeneperma.png",
    category: "Capelli",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-1.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    id: 37,
    title: "NEUTRALIZZANTE - BIONDO BEIGE",
    format: "200 ML",
    subCategory: "Decolorazione",
    price: 19.0,
    brand: "Eugeneperma",
    brandLogo: "/logoEugeneperma.png",
    category: "Capelli",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-1.jpg",
    region: ["Abruzzo", "Lazio"],
  },

  {
    id: 38,
    title: "EQUIVITAL BASE LAVANTE CONCENTRATA",
    format: "5000 ML",
    subCategory: "COMPLEMENTI TECNICI",
    price: 99.0,
    brand: "Eugeneperma",
    brandLogo: "/logoEugeneperma.png",
    category: "Capelli",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-1.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    id: 39,
    title: "EQUIVITAL SHAMPOO POST-COLORAZIONE",
    format: "1000 ML",
    subCategory: "COMPLEMENTI TECNICI",
    price: 23.75,
    brand: "Eugeneperma",
    brandLogo: "/logoEugeneperma.png",
    category: "Capelli",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-1.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    id: 40,
    title: "EQUIVITAL TRATTAMENTO POST-COLORAZIONE",
    format: "1000 ML",
    subCategory: "COMPLEMENTI TECNICI",
    price: 51.1,
    brand: "Eugeneperma",
    brandLogo: "/logoEugeneperma.png",
    category: "Capelli",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-1.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    id: 41,
    title: "EQUIVITAL SMACCHIATORE",
    format: "250 ML",
    subCategory: "COMPLEMENTI TECNICI",
    price: 11.4,
    brand: "Eugeneperma",
    brandLogo: "/logoEugeneperma.png",
    category: "Capelli",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-1.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    id: 42,
    title: "EQUIVITAL CREMA BARRIERA",
    format: "100 ML",
    subCategory: "COMPLEMENTI TECNICI",
    price: 14.05,
    brand: "Eugeneperma",
    brandLogo: "/logoEugeneperma.png",
    category: "Capelli",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-1.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    id: 43,
    title: "EQUIVITAL SHAMPOO PRE-PERMANENTE",
    format: "1000 ML",
    subCategory: "COMPLEMENTI TECNICI",
    price: 42.1,
    brand: "Eugeneperma",
    brandLogo: "/logoEugeneperma.png",
    category: "Capelli",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-1.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    id: 44,
    title: "CURL CREAM",
    format: "50 mL",
    subCategory: "COMPLEMENTI TECNICI",
    price: 9.75,
    brand: "Eugeneperma",
    brandLogo: "/logoEugeneperma.png",
    category: "Capelli",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-1.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    id: 45,
    title: "CURL CREAM",
    format: "150 mL",
    subCategory: "COMPLEMENTI TECNICI",
    price: 14.55,
    brand: "Eugeneperma",
    brandLogo: "/logoEugeneperma.png",
    category: "Capelli",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-1.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    id: 46,
    title: "CURL MOUSSE",
    format: "200 mL",
    subCategory: "COMPLEMENTI TECNICI",
    price: 14.55,
    brand: "Eugeneperma",
    brandLogo: "/logoEugeneperma.png",
    category: "Capelli",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-1.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    id: 47,
    title: "CURL SPRAY",
    format: "200 mL",
    subCategory: "COMPLEMENTI TECNICI",
    price: 18.0,
    brand: "Eugeneperma",
    brandLogo: "/logoEugeneperma.png",
    category: "Capelli",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-1.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    id: 48,
    title: "VOLUME MOUSSE",
    format: "200 mL",
    subCategory: "COMPLEMENTI TECNICI",
    price: 14.55,
    brand: "Eugeneperma",
    brandLogo: "/logoEugeneperma.png",
    category: "Capelli",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-1.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    id: 49,
    title: "VOLUME SPRAY",
    format: "200 mL",
    subCategory: "COMPLEMENTI TECNICI",
    price: 16.15,
    brand: "Eugeneperma",
    brandLogo: "/logoEugeneperma.png",
    category: "Capelli",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-1.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    id: 50,
    title: "LISS'HEAT SPRAY",
    format: "200 mL",
    subCategory: "COMPLEMENTI TECNICI",
    price: 16.15,
    brand: "Eugeneperma",
    brandLogo: "/logoEugeneperma.png",
    category: "Capelli",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-1.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    id: 51,
    title: "SPRAY GLOSS",
    format: "200 mL",
    subCategory: "COMPLEMENTI TECNICI",
    price: 16.15,
    brand: "Eugeneperma",
    brandLogo: "/logoEugeneperma.png",
    category: "Capelli",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-1.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    id: 52,
    title: "TEXTURE PASTE",
    format: "150 mL",
    subCategory: "COMPLEMENTI TECNICI",
    price: 14.55,
    brand: "Eugeneperma",
    brandLogo: "/logoEugeneperma.png",
    category: "Capelli",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-1.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    id: 53,
    title: "MOLDING WAX",
    format: "75 gr",
    subCategory: "COMPLEMENTI TECNICI",
    price: 15.2,
    brand: "Eugeneperma",
    brandLogo: "/logoEugeneperma.png",
    category: "Capelli",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-1.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    id: 54,
    title: "FLEXI BALM",
    format: "125 gr",
    subCategory: "COMPLEMENTI TECNICI",
    price: 15.2,
    brand: "Eugeneperma",
    brandLogo: "/logoEugeneperma.png",
    category: "Capelli",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-1.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    id: 55,
    title: "FIXER GUM",
    format: "75 gr",
    subCategory: "COMPLEMENTI TECNICI",
    price: 18.0,
    brand: "Eugeneperma",
    brandLogo: "/logoEugeneperma.png",
    category: "Capelli",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-1.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    id: 56,
    title: "XTRA STRONG SPRAY",
    format: "200 mL",
    subCategory: "COMPLEMENTI TECNICI",
    price: 16.6,
    brand: "Eugeneperma",
    brandLogo: "/logoEugeneperma.png",
    category: "Capelli",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-1.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    id: 57,
    title: "FIXING MOUSSE",
    format: "200 mL",
    subCategory: "COMPLEMENTI TECNICI",
    price: 14.55,
    brand: "Eugeneperma",
    brandLogo: "/logoEugeneperma.png",
    category: "Capelli",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-1.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    id: 58,
    title: "HAIRSCULPTING SPRAY",
    format: "200 mL",
    subCategory: "COMPLEMENTI TECNICI",
    price: 15.2,
    brand: "Eugeneperma",
    brandLogo: "/logoEugeneperma.png",
    category: "Capelli",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-1.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    id: 59,
    title: "HAIRSCULPTING SPRAY",
    format: "1000 mL",
    subCategory: "COMPLEMENTI TECNICI",
    price: 44.4,
    brand: "Eugeneperma",
    brandLogo: "/logoEugeneperma.png",
    category: "Capelli",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-1.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    id: 60,
    title: "MODELING SPRAY",
    format: "300 mL",
    subCategory: "COMPLEMENTI TECNICI",
    price: 17.5,
    brand: "Eugeneperma",
    brandLogo: "/logoEugeneperma.png",
    category: "Capelli",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-1.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    id: 61,
    title: "MODELING SPRAY",
    format: "500 mL",
    subCategory: "COMPLEMENTI TECNICI",
    price: 24.6,
    brand: "Eugeneperma",
    brandLogo: "/logoEugeneperma.png",
    category: "Capelli",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-1.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    id: 62,
    title: "XTRA STRONG GEL",
    format: "150 mL",
    subCategory: "COMPLEMENTI TECNICI",
    price: 18.0,
    brand: "Eugeneperma",
    brandLogo: "/logoEugeneperma.png",
    category: "Capelli",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-1.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    id: 63,
    title: "FINISHING SPRAY - IN ARRIVO",
    format: "75 mL",
    subCategory: "COMPLEMENTI TECNICI",
    price: 10.65,
    brand: "Eugeneperma",
    brandLogo: "/logoEugeneperma.png",
    category: "Capelli",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-1.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    title: "FINISHING SPRAY",
    format: "300 mL",
    subCategory: "COMPLEMENTI TECNICI",
    price: 17.5,
    brand: "Eugeneperma",
    brandLogo: "/logoEugeneperma.png",
    category: "Capelli",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-1.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    title: "FINISHING SPRAY",
    format: "500 mL",
    subCategory: "COMPLEMENTI TECNICI",
    price: 24.6,
    brand: "Eugeneperma",
    brandLogo: "/logoEugeneperma.png",
    category: "Capelli",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-1.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    title: "SHAMPOO NUTRIZIONE",
    format: "100 ML",
    subCategory: "NUTRIZIONE",
    price: 12.7,
    brand: "Eugeneperma",
    brandLogo: "/logoEugeneperma.png",
    category: "Capelli",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-1.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    title: "SHAMPOO NUTRIZIONE",
    format: "300 ML",
    subCategory: "NUTRIZIONE",
    price: 15.4,
    brand: "Eugeneperma",
    brandLogo: "/logoEugeneperma.png",
    category: "Capelli",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-1.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    title: "SHAMPOO NUTRIZIONE",
    format: "1000 ML",
    subCategory: "NUTRIZIONE",
    price: 38.9,
    brand: "Eugeneperma",
    brandLogo: "/logoEugeneperma.png",
    category: "Capelli",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-1.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    title: "MASK NUTRIZIONE",
    format: "75 ML",
    subCategory: "NUTRIZIONE",
    price: 12.1,
    brand: "Eugeneperma",
    brandLogo: "/logoEugeneperma.png",
    category: "Capelli",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-1.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    title: "MASK NUTRIZIONE",
    format: "250 ML",
    subCategory: "NUTRIZIONE",
    price: 23.45,
    brand: "Eugeneperma",
    brandLogo: "/logoEugeneperma.png",
    category: "Capelli",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-1.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    title: "MASK NUTRIZIONE",
    format: "500 ML",
    subCategory: "NUTRIZIONE",
    price: 45.05,
    brand: "Eugeneperma",
    brandLogo: "/logoEugeneperma.png",
    category: "Capelli",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-1.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    title: "SHAMPOO USO FREQUENTE",
    format: "300 ML",
    subCategory: "USO FREQUENTE - IDRATAZIONE",
    price: 15.4,
    brand: "Eugeneperma",
    brandLogo: "/logoEugeneperma.png",
    category: "Capelli",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-1.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    title: "SHAMPOO USO FREQUENTE",
    format: "1000 ML",
    subCategory: "USO FREQUENTE - IDRATAZIONE",
    price: 38.9,
    brand: "Eugeneperma",
    brandLogo: "/logoEugeneperma.png",
    category: "Capelli",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-1.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    title: "MASK USO FREQUENTE",
    format: "75 ML",
    subCategory: "USO FREQUENTE - IDRATAZIONE",
    price: 12.1,
    brand: "Eugeneperma",
    brandLogo: "/logoEugeneperma.png",
    category: "Capelli",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-1.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    title: "MASK USO FREQUENTE",
    format: "250 ML",
    subCategory: "USO FREQUENTE - IDRATAZIONE",
    price: 23.45,
    brand: "Eugeneperma",
    brandLogo: "/logoEugeneperma.png",
    category: "Capelli",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-1.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    title: "MASK USO FREQUENTE",
    format: "500 ML",
    subCategory: "USO FREQUENTE - IDRATAZIONE",
    price: 45.05,
    brand: "Eugeneperma",
    brandLogo: "/logoEugeneperma.png",
    category: "Capelli",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-1.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    title: "SPRAY USO FREQUENTE PROTETTIVO",
    format: "200 ML",
    subCategory: "USO FREQUENTE - IDRATAZIONE",
    price: 21.8,
    brand: "Eugeneperma",
    brandLogo: "/logoEugeneperma.png",
    category: "Capelli",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-1.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  // Lista de productos...
  {
    title: "TRATTAMENTO VOLUME",
    format: "12 x 6 ML",
    subCategory: "VOLUME",
    price: 59.65,
    brand: "Eugeneperma",
    brandLogo: "/logoEugeneperma.png",
    category: "Capelli",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-1.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    title: "SHAMPOO VOLUME",
    format: "300 ML",
    subCategory: "VOLUME",
    price: 15.4,
    brand: "Eugeneperma",
    brandLogo: "/logoEugeneperma.png",
    category: "Capelli",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-1.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    title: "SHAMPOO VOLUME",
    format: "1000 ML",
    subCategory: "VOLUME",
    price: 38.9,
    brand: "Eugeneperma",
    brandLogo: "/logoEugeneperma.png",
    category: "Capelli",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-1.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    title: "VOLUME SPRAY",
    format: "200 ML",
    subCategory: "VOLUME",
    price: 21.8,
    brand: "Eugeneperma",
    brandLogo: "/logoEugeneperma.png",
    category: "Capelli",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-1.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    title: "SHAMPOO COLOR",
    format: "100 ML",
    subCategory: "COLORE",
    price: 12.7,
    brand: "Eugeneperma",
    brandLogo: "/logoEugeneperma.png",
    category: "Capelli",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-1.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    title: "SHAMPOO COLOR",
    format: "300 ML",
    subCategory: "COLORE",
    price: 15.4,
    brand: "Eugeneperma",
    brandLogo: "/logoEugeneperma.png",
    category: "Capelli",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-1.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    title: "SHAMPOO COLOR",
    format: "1000 ML",
    subCategory: "COLORE",
    price: 38.9,
    brand: "Eugeneperma",
    brandLogo: "/logoEugeneperma.png",
    category: "Capelli",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-1.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    title: "MASK COLOR",
    format: "75 ML",
    subCategory: "COLORE",
    price: 12.1,
    brand: "Eugeneperma",
    brandLogo: "/logoEugeneperma.png",
    category: "Capelli",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-1.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    title: "MASK COLOR",
    format: "250 ML",
    subCategory: "COLORE",
    price: 23.45,
    brand: "Eugeneperma",
    brandLogo: "/logoEugeneperma.png",
    category: "Capelli",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-1.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    title: "COLOR MASK",
    format: "500 ML",
    subCategory: "COLORE",
    price: 45.05,
    brand: "Eugeneperma",
    brandLogo: "/logoEugeneperma.png",
    category: "Capelli",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-1.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    title: "COLOR CARE SPRAY",
    format: "200 ML",
    subCategory: "COLORE",
    price: 21.8,
    brand: "Eugeneperma",
    brandLogo: "/logoEugeneperma.png",
    category: "Capelli",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-1.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    title: "SHAMPOO SILVER",
    format: "300 ML",
    subCategory: "SILVER",
    price: 15.4,
    brand: "Eugeneperma",
    brandLogo: "/logoEugeneperma.png",
    category: "Capelli",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-1.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    title: "SHAMPOO SILVER",
    format: "1000 ML",
    subCategory: "SILVER",
    price: 38.9,
    brand: "Eugeneperma",
    brandLogo: "/logoEugeneperma.png",
    category: "Capelli",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-1.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    title: "SHAMPOO ANTI-FORFORA",
    format: "300 ML",
    subCategory: "ANTI FORFORA",
    price: 15.4,
    brand: "Eugeneperma",
    brandLogo: "/logoEugeneperma.png",
    category: "Capelli",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-1.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    title: "SHAMPOO ANTI-FORFORA",
    format: "1000 ML",
    subCategory: "ANTI FORFORA",
    price: 38.9,
    brand: "Eugeneperma",
    brandLogo: "/logoEugeneperma.png",
    category: "Capelli",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-1.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    title: "LACCA TENUTA NORMALE",
    format: "300 ML",
    subCategory: "STYLING",
    price: 17.35,
    brand: "Eugeneperma",
    brandLogo: "/logoEugeneperma.png",
    category: "Capelli",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-1.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    title: "LACCA TENUTA NORMALE",
    format: "500 ML",
    subCategory: "STYLING",
    price: 19.65,
    brand: "Eugeneperma",
    brandLogo: "/logoEugeneperma.png",
    category: "Capelli",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-1.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    title: "LACCA TENUTA FORTE",
    format: "300 ML",
    subCategory: "STYLING",
    price: 17.35,
    brand: "Eugeneperma",
    brandLogo: "/logoEugeneperma.png",
    category: "Capelli",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-1.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    title: "LACCA TENUTA FORTE",
    format: "500 ML",
    subCategory: "STYLING",
    price: 19.65,
    brand: "Eugeneperma",
    brandLogo: "/logoEugeneperma.png",
    category: "Capelli",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-1.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    title: "SUPER DETANGLING SHAMPOO",
    format: "300 ML",
    subCategory: "SUPER DISTRICANTE",
    price: 17.6,
    brand: "Eugeneperma",
    brandLogo: "/logoEugeneperma.png",
    category: "Capelli",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-1.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    title: "SUPER DETANGLING SPRAY",
    format: "125 ML",
    subCategory: "SUPER DISTRICANTE",
    price: 17.2,
    brand: "Eugeneperma",
    brandLogo: "/logoEugeneperma.png",
    category: "Capelli",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-1.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    title: "SHAMPOO PURIFICANTE",
    format: "300 ML",
    subCategory: "PURIFICANTE",
    price: 15.4,
    brand: "Eugeneperma",
    brandLogo: "/logoEugeneperma.png",
    category: "Capelli",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-1.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    title: "SHAMPOO PURIFICANTE",
    format: "1000 ML",
    subCategory: "PURIFICANTE",
    price: 38.9,
    brand: "Eugeneperma",
    brandLogo: "/logoEugeneperma.png",
    category: "Capelli",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-1.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    title: "BARRETTA SHAMPOO PURIFICANTE",
    format: "85 GR",
    subCategory: "SHAMPOO SOLIDO",
    price: 10.35,
    brand: "Eugeneperma",
    brandLogo: "/logoEugeneperma.png",
    category: "Capelli",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-1.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    title: "BARRETTA SHAMPOO ADDOLCENTE",
    format: "85 GR",
    subCategory: "SHAMPOO SOLIDO",
    price: 10.35,
    brand: "Eugeneperma",
    brandLogo: "/logoEugeneperma.png",
    category: "Capelli",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-1.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    title: "ESSENTIEL KERATIN GOLD SHAMPOO",
    format: "100 ML",
    subCategory: "CAPELLI FRAGILI",
    price: 11.8,
    brand: "Eugeneperma",
    brandLogo: "/logoEugeneperma.png",
    category: "Capelli",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-1.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    title: "ESSENTIEL KERATIN GOLD SHAMPOO",
    format: "250 ML",
    subCategory: "CAPELLI FRAGILI",
    price: 15.25,
    brand: "Eugeneperma",
    brandLogo: "/logoEugeneperma.png",
    category: "Capelli",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-1.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    title: "ESSENTIEL KERATIN GOLD SHAMPOO",
    format: "1000 ML",
    subCategory: "CAPELLI FRAGILI",
    price: 42.25,
    brand: "Eugeneperma",
    brandLogo: "/logoEugeneperma.png",
    category: "Capelli",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-1.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    title: "ESSENTIEL KERATIN GOLD MASK",
    format: "50 ML",
    subCategory: "CAPELLI FRAGILI",
    price: 10.2,
    brand: "Eugeneperma",
    brandLogo: "/logoEugeneperma.png",
    category: "Capelli",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-1.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    title: "ESSENTIEL KERATIN GOLD MASK",
    format: "150 ML",
    subCategory: "CAPELLI FRAGILI",
    price: 22.65,
    brand: "Eugeneperma",
    brandLogo: "/logoEugeneperma.png",
    category: "Capelli",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-1.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    title: "ESSENTIEL KERATIN GOLD MASK",
    format: "500 ML",
    subCategory: "CAPELLI FRAGILI",
    price: 49.95,
    brand: "Eugeneperma",
    brandLogo: "/logoEugeneperma.png",
    category: "Capelli",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-1.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    title: "ESSENTIEL KERATIN GOLD TRATTAMENTO BOOSTER",
    format: "10 X 10 ML",
    subCategory: "CAPELLI FRAGILI",
    price: 57.65,
    brand: "Eugeneperma",
    brandLogo: "/logoEugeneperma.png",
    category: "Capelli",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-1.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    title: "ESSENTIEL KERATIN GLOW SHAMPOO",
    format: "250 ML",
    subCategory: "TUTTI TIPI Di CAPELLI",
    price: 15.25,
    brand: "Eugeneperma",
    brandLogo: "/logoEugeneperma.png",
    category: "Capelli",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-1.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    title: "ESSENTIEL KERATIN GLOW SHAMPOO",
    format: "1000 ML",
    subCategory: "TUTTI TIPI Di CAPELLI",
    price: 42.25,
    brand: "Eugeneperma",
    brandLogo: "/logoEugeneperma.png",
    category: "Capelli",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-1.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    title: "ESSENTIEL KERATIN GLOW MASK",
    format: "150 ML",
    subCategory: "TUTTI TIPI Di CAPELLI",
    price: 22.65,
    brand: "Eugeneperma",
    brandLogo: "/logoEugeneperma.png",
    category: "Capelli",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-1.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    title: "ESSENTIEL KERATIN GLOW MASK",
    format: "500 ML",
    subCategory: "TUTTI TIPI Di CAPELLI",
    price: 49.95,
    brand: "Eugeneperma",
    brandLogo: "/logoEugeneperma.png",
    category: "Capelli",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-1.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    title: "ESSENTIEL SERUM LEAVE-IN",
    format: "50 ML",
    subCategory: "TUTTI TIPI Di CAPELLI",
    price: 35.6,
    brand: "Eugeneperma",
    brandLogo: "/logoEugeneperma.png",
    category: "Capelli",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-1.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    title: "ESSENTIEL KERATIN PULP CONDITIONNER PRE LAVAGGIO",
    format: "200 ML",
    subCategory: "CAPELLI FINI",
    price: 22.85,
    brand: "Eugeneperma",
    brandLogo: "/logoEugeneperma.png",
    category: "Capelli",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-1.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    title: "ESSENTIEL KERATIN PULP SHAMPOO",
    format: "250 ML",
    subCategory: "CAPELLI FINI",
    price: 15.25,
    brand: "Eugeneperma",
    brandLogo: "/logoEugeneperma.png",
    category: "Capelli",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-1.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    title: "ESSENTIEL KERATIN PULP SHAMPOO",
    format: "1000 ML",
    subCategory: "CAPELLI FINI",
    price: 42.25,
    brand: "Eugeneperma",
    brandLogo: "/logoEugeneperma.png",
    category: "Capelli",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-1.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    title: "ESSENTIEL KERATIN FRIZZ 2 IN 1 CARE SHAMPOO",
    format: "400 ML",
    subCategory: "CAPELLI RICCI",
    price: 30.75,
    brand: "Eugeneperma",
    brandLogo: "/logoEugeneperma.png",
    category: "Capelli",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-1.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    title: "ESSENTIEL KERATIN FRIZZ 2 IN 1 CARE SHAMPOO",
    format: "1000 ML",
    subCategory: "CAPELLI RICCI",
    price: 42.25,
    brand: "Eugeneperma",
    brandLogo: "/logoEugeneperma.png",
    category: "Capelli",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-1.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    title: "ESSENTIEL KERATIN  EXPRESS OLIO",
    format: "200 ML",
    subCategory: "CAPELLI RICCI",
    price: 22.3,
    brand: "Eugeneperma",
    brandLogo: "/logoEugeneperma.png",
    category: "Capelli",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-1.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    title: "ESSENTIEL KERATIN NUTRI SHAMPOO",
    format: "250 ML",
    subCategory: "CAPELLI SECCHI",
    price: 15.25,
    brand: "Eugeneperma",
    brandLogo: "/logoEugeneperma.png",
    category: "Capelli",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-1.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    title: "ESSENTIEL KERATIN NUTRI SHAMPOO",
    format: "1000 ML",
    subCategory: "CAPELLI SECCHI",
    price: 42.25,
    brand: "Eugeneperma",
    brandLogo: "/logoEugeneperma.png",
    category: "Capelli",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-1.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    title: "ESSENTIEL KERATIN NUTRI MASK",
    format: "150 ML",
    subCategory: "CAPELLI SECCHI",
    price: 22.65,
    brand: "Eugeneperma",
    brandLogo: "/logoEugeneperma.png",
    category: "Capelli",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-1.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    title: "ESSENTIEL KERATIN NUTRI MASK",
    format: "500 ML",
    subCategory: "CAPELLI SECCHI",
    price: 49.95,
    brand: "Eugeneperma",
    brandLogo: "/logoEugeneperma.png",
    category: "Capelli",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-1.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    title: "ESSENTIEL KERATIN NUTRI SERUM",
    format: "200 ML",
    subCategory: "CAPELLI SECCHI",
    price: 39.2,
    brand: "Eugeneperma",
    brandLogo: "/logoEugeneperma.png",
    category: "Capelli",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-1.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    title: "ESSENTIEL NUTRITION OLIO",
    format: "100 ML",
    subCategory: "CAPELLI SECCHI",
    price: 35.6,
    brand: "Eugeneperma",
    brandLogo: "/logoEugeneperma.png",
    category: "Capelli",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-1.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    title: "ESSENTIEL KERATIN COLOR SHAMPOO",
    format: "100 ML",
    subCategory: "COLOR CAPELLI COLORATI",
    price: 11.8,
    brand: "Eugeneperma",
    brandLogo: "/logoEugeneperma.png",
    category: "Capelli",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-1.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    title: "ESSENTIEL KERATIN COLOR SHAMPOO",
    format: "250 ML",
    subCategory: "COLOR CAPELLI COLORATI",
    price: 15.25,
    brand: "Eugeneperma",
    brandLogo: "/logoEugeneperma.png",
    category: "Capelli",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-1.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    title: "ESSENTIEL KERATIN COLOR SHAMPOO",
    format: "1000 ML",
    subCategory: "COLOR CAPELLI COLORATI",
    price: 42.25,
    brand: "Eugeneperma",
    brandLogo: "/logoEugeneperma.png",
    category: "Capelli",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-1.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    title: "ESSENTIEL KERATIN COLOR MASK",
    format: "50 ML",
    subCategory: "COLOR CAPELLI COLORATI",
    price: 10.2,
    brand: "Eugeneperma",
    brandLogo: "/logoEugeneperma.png",
    category: "Capelli",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-1.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    title: "ESSENTIEL KERATIN COLOR MASK",
    format: "150 ML",
    subCategory: "COLOR CAPELLI COLORATI",
    price: 22.65,
    brand: "Eugeneperma",
    brandLogo: "/logoEugeneperma.png",
    category: "Capelli",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-1.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    title: "ESSENTIEL KERATIN COLOR MASK",
    format: "500 ML",
    subCategory: "COLOR CAPELLI COLORATI",
    price: 49.95,
    brand: "Eugeneperma",
    brandLogo: "/logoEugeneperma.png",
    category: "Capelli",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-1.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    title: "ESSENTIEL KERATIN COLOR SPRAY BI-FASE",
    format: "200 ML",
    subCategory: "COLOR CAPELLI COLORATI",
    price: 23.05,
    brand: "Eugeneperma",
    brandLogo: "/logoEugeneperma.png",
    category: "Capelli",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-1.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    title: "ESSENTIEL KERATIN SILVER SHAMPOO",
    format: "250 ML",
    subCategory: "SILVER CAPELLI BIONDI-DEC-BIANCHI",
    price: 15.25,
    brand: "Eugeneperma",
    brandLogo: "/logoEugeneperma.png",
    category: "Capelli",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-1.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    title: "ESSENTIEL KERATIN SILVER SHAMPOO",
    format: "1000 ML",
    subCategory: "SILVER CAPELLI BIONDI-DEC-BIANCHI",
    price: 42.25,
    brand: "Eugeneperma",
    brandLogo: "/logoEugeneperma.png",
    category: "Capelli",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-1.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    title: "ESSENTIEL KERATIN FORCE SHAMPOO",
    format: "250 ML",
    subCategory: "ANTICADUTA",
    price: 15.25,
    brand: "Eugeneperma",
    brandLogo: "/logoEugeneperma.png",
    category: "Capelli",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-1.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    title: "ESSENTIEL KERATIN FORCE SHAMPOO",
    format: "1000 ML",
    subCategory: "ANTICADUTA",
    price: 42.25,
    brand: "Eugeneperma",
    brandLogo: "/logoEugeneperma.png",
    category: "Capelli",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-1.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    title: "ESSENTIEL KERATIN FORCE FIALE",
    format: "12 x 3,5 ML",
    subCategory: "ANTICADUTA",
    price: 67.05,
    brand: "Eugeneperma",
    brandLogo: "/logoEugeneperma.png",
    category: "Capelli",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-1.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    title: "ESSENTIEL KERATIN FORCE SPRAY",
    format: "200 ML",
    subCategory: "ANTICADUTA",
    price: 41.45,
    brand: "Eugeneperma",
    brandLogo: "/logoEugeneperma.png",
    category: "Capelli",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-1.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    title: "ESSENTIEL KERATIN SENSITIVE SHAMPOO",
    format: "250 ML",
    subCategory: "CUTE SENSIBILE",
    price: 15.25,
    brand: "Eugeneperma",
    brandLogo: "/logoEugeneperma.png",
    category: "Capelli",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-1.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    title: "ESSENTIEL KERATIN SENSITIVE SHAMPOO",
    format: "1000 ML",
    subCategory: "CUTE SENSIBILE",
    price: 42.25,
    brand: "Eugeneperma",
    brandLogo: "/logoEugeneperma.png",
    category: "Capelli",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-1.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    title: "ESSENTIEL KERATIN SENSITIVE SIERO",
    format: "40 ML",
    subCategory: "CUTE SENSIBILE",
    price: 25.65,
    brand: "Eugeneperma",
    brandLogo: "/logoEugeneperma.png",
    category: "Capelli",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-1.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    title: "ESSENTIEL SHAMPOO KERATIN BALANCE",
    format: "250 ML",
    subCategory: "CAPELLI GRASSI",
    price: 15.25,
    brand: "Eugeneperma",
    brandLogo: "/logoEugeneperma.png",
    category: "Capelli",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-1.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    title: "ESSENTIEL SHAMPOO KERATIN BALANCE",
    format: "1000 ML",
    subCategory: "CAPELLI GRASSI",
    price: 42.25,
    brand: "Eugeneperma",
    brandLogo: "/logoEugeneperma.png",
    category: "Capelli",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-1.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    title: "ESSENTIEL CONDITIONER KERATIN BALANCE",
    format: "200 ML",
    subCategory: "CAPELLI GRASSI",
    price: 22.8,
    brand: "Eugeneperma",
    brandLogo: "/logoEugeneperma.png",
    category: "Capelli",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-1.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    title: "ESSENTIEL ARGILLA LAVANTE KERATIN BALANCE",
    format: "250 ML",
    subCategory: "CAPELLI GRASSI",
    price: 19.6,
    brand: "Eugeneperma",
    brandLogo: "/logoEugeneperma.png",
    category: "Capelli",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-1.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    title: "ESSENTIEL KERATIN SUN SHAMPOO",
    format: "250 ML",
    subCategory: "SUN",
    price: 15.25,
    brand: "Eugeneperma",
    brandLogo: "/logoEugeneperma.png",
    category: "Capelli",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-1.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    title: "ESSENTIEL KERATIN SUN 2-IN-1 MASK",
    format: "150 ML",
    subCategory: "SUN",
    price: 21.2,
    brand: "Eugeneperma",
    brandLogo: "/logoEugeneperma.png",
    category: "Capelli",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-1.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    title: "ESSENTIEL PROTECTION MIST - IN ARRIVO -",
    format: "150 ML",
    subCategory: "SUN",
    price: 21.2,
    brand: "Eugeneperma",
    brandLogo: "/logoEugeneperma.png",
    category: "Capelli",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-1.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    id: 100,
    title: "Liposome Hair Color - BIG",
    price: 65.0,
    format: "1 pz",
    subsubCategory: "Accessori",
    category: "Accessori",
    brand: "Chenice",
    brandLogo: "/logoChenice.png",
    newFlag: false,
    favorite: false,
    bestseller: false,
    image: "/products/image-3.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    title: "CARTELLA COLORI Liposome Hair Color - SMALL",
    price: 23.5,
    format: "1 pz",
    subCategory: "Accessori",
    category: "Accessori",
    brand: "Chenice",
    brandLogo: "/logoChenice.png",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-3.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    title: "BACINELLA Liposome Hair Color",
    price: 1.4,
    format: "1 pz",
    subCategory: "Accessori",
    category: "Accessori",
    brand: "Chenice",
    brandLogo: "/logoChenice.png",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-3.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    title: "PENNELLO Liposome Hair Color",
    price: 1.25,
    format: "1 pz",
    subCategory: "Accessori",
    category: "Accessori",
    brand: "Chenice",
    brandLogo: "/logoChenice.png",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-3.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    title: "CARTELLA COLORI Botanical",
    price: 43.0,
    format: "1 pz",
    subCategory: "Accessori",
    category: "Accessori",
    brand: "Chenice",
    brandLogo: "/logoChenice.png",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-3.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    title: "MANTELLINE MONOUSO",
    price: 5.5,
    format: "Confezione 30 pz",
    subCategory: "Accessori",
    category: "Accessori",
    brand: "Chenice",
    brandLogo: "/logoChenice.png",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-3.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    title: "PHON CHENICE",
    price: 89.0,
    format: "1 pz",
    subCategory: "Accessori",
    category: "Accessori",
    brand: "Chenice",
    brandLogo: "/logoChenice.png",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-3.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    title: "FERRO ARRICCIACAPELLI",
    price: 158.0,
    format: "1 pz",
    subCategory: "Accessori",
    category: "Accessori",
    brand: "Chenice",
    brandLogo: "/logoChenice.png",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-3.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    title: "ANTI-AGE C18 100 ml.",
    price: 39.5,
    format: "6 FLACONE",
    subCategory: "ANTI-AGE",
    category: "Capelli",
    brand: "Chenice",
    brandLogo: "/logoChenice.png",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-3.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    title: "ANTI-AGE C18 50 ml.",
    price: 28.0,
    format: "6 FLACONE",
    subCategory: "ANTI-AGE",
    category: "Capelli",
    brand: "Chenice",
    brandLogo: "/logoChenice.png",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-3.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    title: "DISPLAY ANTI-AGE",
    price: 16.0,
    format: "1 pz",
    subCategory: "ANTI-AGE",
    category: "Capelli",
    brand: "Chenice",
    brandLogo: "/logoChenice.png",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-3.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    title: "POSTER ANTI-AGE",
    price: 1.9,
    format: "1 pz",
    subCategory: "ANTI-AGE",
    category: "Capelli",
    brand: "Chenice",
    brandLogo: "/logoChenice.png",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-3.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    title: "DEPLIANT ANTI-AGE",
    price: 2.4,
    format: "1 pz",
    subCategory: "ANTI-AGE",

    category: "Capelli",
    brand: "Chenice",
    brandLogo: "/logoChenice.png",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-3.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    title: "KIT GREEN CARE",
    price: 55.0,
    format: "1 KIT",
    subCategory: "GREEN CARE",
    category: "Capelli",
    brand: "Chenice",
    brandLogo: "/logoChenice.png",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-3.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    title: "SANITIZING TREATMENT NR 1 100ml",
    price: 96.0,
    format: "6 FLACONE",
    subCategory: "GREEN CARE",
    category: "Capelli",
    brand: "Chenice",
    brandLogo: "/logoChenice.png",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-3.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    title: "VITAMIN SHAMPOO NR 2 250ml",
    price: 108.0,
    format: "6 FLACONE",
    subCategory: "GREEN CARE",
    category: "Capelli",
    brand: "Chenice",
    brandLogo: "/logoChenice.png",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-3.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    title: "VITAMIN LOTION NR 3 100ml",
    price: 126.0,
    format: "6 FLACONE",
    subCategory: "GREEN CARE",
    category: "Capelli",
    brand: "Chenice",
    brandLogo: "/logoChenice.png",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-3.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    title: "DEPLIANT GREEN CARE",
    price: 2.4,
    format: "1 pz",
    subCategory: "GREEN CARE",
    category: "Capelli",
    brand: "Chenice",
    brandLogo: "/logoChenice.png",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-3.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    title: "BIOLOGICAL WAVES 100 ml",
    price: 19.5,
    format: "1 KIT (PERM+NEUTR)",
    subCategory: "BIOLOGICAL WAVES",
    category: "Capelli",
    brand: "Chenice",
    brandLogo: "/logoChenice.png",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-3.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    title: "BROCHURE BWS",
    price: 2.45,
    format: "1 pz",
    subCategory: "BIOLOGICAL WAVES",
    category: "Capelli",
    brand: "Chenice",
    brandLogo: "/logoChenice.png",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-3.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    title: "POSTER BWS",
    price: 1.8,
    format: "1 pz",
    subCategory: "BIOLOGICAL WAVES",
    category: "Capelli",
    brand: "Chenice",
    brandLogo: "/logoChenice.png",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-3.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    title: "AQUA WAX 100 ml",
    price: 15.0,
    format: "6 VASO",
    subCategory: "IFIX",
    category: "Capelli",
    brand: "Chenice",
    brandLogo: "/logoChenice.png",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-3.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    title: "CURLS WAVE 100 ml",
    price: 14.8,
    format: "6 VASO",
    subCategory: "IFIX",
    category: "Capelli",
    brand: "Chenice",
    brandLogo: "/logoChenice.png",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-3.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    title: "SHAPE-IT 100 ml",
    price: 16.5,
    format: "6 VASO",
    subCategory: "IFIX",
    category: "Capelli",
    brand: "Chenice",
    brandLogo: "/logoChenice.png",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-3.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    title: "FIX IT GEL 200 ml",
    price: 16.0,
    format: "6 TUBO",
    subCategory: "IFIX",
    category: "Capelli",
    brand: "Chenice",
    brandLogo: "/logoChenice.png",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-3.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    title: "WET LOOK GEL 200 ml",
    price: 12.0,
    format: "6 TUBO",
    subCategory: "IFIX",
    category: "Capelli",
    brand: "Chenice",
    brandLogo: "/logoChenice.png",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-3.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    title: "FORMING LACQUER Strong 300 ml",
    price: 19.5,
    format: "12 BOMBOLA",
    subCategory: "IFIX",
    category: "Capelli",
    brand: "Chenice",
    brandLogo: "/logoChenice.png",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-3.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    title: "VOLUMIZING MOUSSE Strong 300 ml",
    price: 16.5,
    format: "12 BOMBOLA",
    subCategory: "IFIX",
    category: "Capelli",
    brand: "Chenice",
    brandLogo: "/logoChenice.png",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-3.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    title: "POWER SHINE 500 ml",
    price: 19.0,
    format: "12 BOMBOLA",
    subCategory: "IFIX",
    category: "Capelli",
    brand: "Chenice",
    brandLogo: "/logoChenice.png",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-3.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    title: "POWER SHINE 75 ml",
    price: 5.95,
    format: "12 BOMBOLA",
    subCategory: "IFIX",
    category: "Capelli",
    brand: "Chenice",
    brandLogo: "/logoChenice.png",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-3.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    title: "FORMING GLAZE 150 ml",
    price: 13.0,
    format: "6 FLACONE",
    subCategory: "IFIX",
    category: "Capelli",
    brand: "Chenice",
    brandLogo: "/logoChenice.png",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-3.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    title: "PURE VOLUME 150 ml",
    price: 14.8,
    format: "6 FLACONE",
    subCategory: "IFIX",
    category: "Capelli",
    brand: "Chenice",
    brandLogo: "/logoChenice.png",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-3.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    title: "POLISHING SERUM 150 ml",
    price: 28.0,
    format: "6 FLACONE",
    subCategory: "IFIX",
    category: "Capelli",
    brand: "Chenice",
    brandLogo: "/logoChenice.png",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-3.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    title: "PURIFYING SHAMPOO 1 lt",
    price: 28.0,
    format: "1 lt. 6 FLACONE",
    subCategory: "URBN",
    category: "Capelli",
    brand: "Chenice",
    brandLogo: "/logoChenice.png",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-3.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    title: "PURIFYING MASK 1 lt",
    price: 29.0,
    format: "1 lt. 6 FLACONE",
    subCategory: "URBN",
    category: "Capelli",
    brand: "Chenice",
    brandLogo: "/logoChenice.png",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-3.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    title: "PURIFYING SHAMPOO 250 ml",
    price: 13.5,
    format: "250 ml. 6 FLACONE",
    subCategory: "URBN",
    category: "Capelli",
    brand: "Chenice",
    brandLogo: "/logoChenice.png",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-3.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    title: "PURIFYING MASK 200 ml",
    price: 14.0,
    format: "200 ml. 6 FLACONE",
    subCategory: "URBN",
    category: "Capelli",
    brand: "Chenice",
    brandLogo: "/logoChenice.png",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-3.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    title: "NOURISHING MOUSSE 200 ml",
    price: 21.0,
    format: "200 ml. 6 FLACONE",
    subCategory: "URBN",
    category: "Capelli",
    brand: "Chenice",
    brandLogo: "/logoChenice.png",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-3.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    title: "NEW URBN WHYTWELVE 150 ml",
    price: 13.0,
    format: "150 ml. 6 FLACONE",
    subCategory: "URBN",
    category: "Capelli",
    brand: "Chenice",
    brandLogo: "/logoChenice.png",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-3.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    title: "URBN DISPLAY 1 pz",
    price: 13.0,
    format: "1 pz",
    subCategory: "URBN",
    category: "Capelli",
    brand: "Chenice",
    brandLogo: "/logoChenice.png",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-3.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    title: "URBN BANNER 1 pz",
    price: 25.0,
    format: "1 pz",
    subCategory: "URBN",
    category: "Capelli",
    brand: "Chenice",
    brandLogo: "/logoChenice.png",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-3.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    title: "URBN POSTER 1 pz",
    price: 1.8,
    format: "1 pz",
    subCategory: "URBN",
    category: "Capelli",
    brand: "Chenice",
    brandLogo: "/logoChenice.png",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-3.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    title: "URBN BROCHURE 1 pz",
    price: 2.4,
    format: "1 pz",
    subCategory: "URBN",
    category: "Capelli",
    brand: "Chenice",
    brandLogo: "/logoChenice.png",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-3.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    title: "KIT BOTTOX 50 ml",
    price: 143.0,
    format: "1 KIT",
    subCategory: "BOTTOX EFFECT",
    category: "Capelli",
    brand: "Chenice",
    brandLogo: "/logoChenice.png",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-3.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    title: "CLARIFYING SHAMPOO 500 ml.",
    price: 17.0,
    format: "1 pz",
    subCategory: "BOTTOX EFFECT",
    category: "Capelli",
    brand: "Chenice",
    brandLogo: "/logoChenice.png",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-3.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    title: "POSTER BOTTOX 1 pz",
    price: 1.85,
    format: "1 pz",
    subCategory: "BOTTOX EFFECT",
    category: "Capelli",
    brand: "Chenice",
    brandLogo: "/logoChenice.png",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-3.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    title: "DEPLIANT BOTTOX 1 pz",
    price: 2.35,
    format: "1 pz",
    subCategory: "BOTTOX EFFECT",
    category: "Capelli",
    brand: "Chenice",
    brandLogo: "/logoChenice.png",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-3.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    title: "MOISTURIZING SHAMPOO",
    formato: "1 Lt.",
    precio: "€ 28,00",
    subCategory: "MOISTURIZING",
    category: "Capelli",
    brand: "Chenice",
    brandLogo: "/logoChenice.png",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-3.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    title: "MOISTURIZING MASK",
    formato: "1 Lt.",
    precio: "€ 34,00",
    subCategory: "MOISTURIZING",
    category: "Capelli",
    brand: "Chenice",
    brandLogo: "/logoChenice.png",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-3.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    title: "MOISTURIZING SHAMPOO",
    formato: "250 ml",
    precio: "€ 14,80",
    subCategory: "MOISTURIZING",
    category: "Capelli",
    brand: "Chenice",
    brandLogo: "/logoChenice.png",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-3.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    title: "MOISTURIZING MASK",
    formato: "200 ml",
    precio: "€ 15,00",
    subCategory: "MOISTURIZING",
    category: "Capelli",
    brand: "Chenice",
    brandLogo: "/logoChenice.png",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-3.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    title: "BLISTERS MOISTURIZING",
    formato: "1 pz",
    precio: "€ 1,20",
    subCategory: "MOISTURIZING",
    category: "Capelli",
    brand: "Chenice",
    brandLogo: "/logoChenice.png",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-3.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    title: "BROCHURE MOISTURIZING",
    formato: "1 pz",
    precio: "€ 2,40",
    subCategory: "MOISTURIZING",
    category: "Capelli",
    brand: "Chenice",
    brandLogo: "/logoChenice.png",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-3.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    title: "POSTER MOISTURIZING",
    formato: "1 pz",
    precio: "€ 1,80",
    subCategory: "MOISTURIZING",
    category: "Capelli",
    brand: "Chenice",
    brandLogo: "/logoChenice.png",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-3.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    title: "SINERGY WASH",
    formato: "1000 ml",
    precio: "€ 29,50",
    subCategory: "FORFORA-GRASSO",
    category: "Capelli",
    brand: "Chenice",
    brandLogo: "/logoChenice.png",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-3.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    title: "SINERGY WASH",
    formato: "250 ml",
    precio: "€ 16,50",
    subCategory: "FORFORA-GRASSO",
    category: "Capelli",
    brand: "Chenice",
    brandLogo: "/logoChenice.png",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-3.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    title: "REGAL WASH",
    formato: "1000 ml",
    precio: "€ 25,00",
    subCategory: "ANTICADUTA",
    category: "Capelli",
    brand: "Chenice",
    brandLogo: "/logoChenice.png",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-3.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    title: "REGAL WASH",
    formato: "250 ml",
    precio: "€ 13,00",
    subCategory: "ANTICADUTA",
    category: "Capelli",
    brand: "Chenice",
    brandLogo: "/logoChenice.png",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-3.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    title: "REGAL WASH",
    formato: "100 ml",
    precio: "€ 6,00",
    subCategory: "ANTICADUTA",
    category: "Capelli",
    brand: "Chenice",
    brandLogo: "/logoChenice.png",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-3.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    title: "REGAL LIFE",
    formato: "12 x 6 ml",
    precio: "€ 42,00",
    subCategory: "ANTICADUTA",
    category: "Capelli",
    brand: "Chenice",
    brandLogo: "/logoChenice.png",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-3.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    title: "REGAL LIFE",
    formato: "4 x 6 ml",
    precio: "€ 18,00",
    subCategory: "ANTICADUTA",
    category: "Capelli",
    brand: "Chenice",
    brandLogo: "/logoChenice.png",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-3.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    title: "HYDRO-KERATIN SHAMPOO",
    formato: "1000 ml",
    precio: "€ 26,00",
    subCategory: "RICOSTRUZIONE",
    category: "Capelli",
    brand: "Chenice",
    brandLogo: "/logoChenice.png",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-3.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    title: "MULTI-VITAMIN OIL",
    formato: "500 ml",
    precio: "€ 31,00",
    subCategory: "RICOSTRUZIONE",
    category: "Capelli",
    brand: "Chenice",
    brandLogo: "/logoChenice.png",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-3.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    title: "KERABONDING MASK",
    formato: "500 ml",
    precio: "€ 23,00",
    subCategory: "RICOSTRUZIONE",
    category: "Capelli",
    brand: "Chenice",
    brandLogo: "/logoChenice.png",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-3.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    title: "HYDRO-KERATIN SHAMPOO",
    formato: "250 ml",
    precio: "€ 13,00",
    subCategory: "RICOSTRUZIONE",
    category: "Capelli",
    brand: "Chenice",
    brandLogo: "/logoChenice.png",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-3.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    title: "MULTI-VITAMIN OIL",
    formato: "150 ml",
    precio: "€ 25,00",
    subCategory: "RICOSTRUZIONE",
    category: "Capelli",
    brand: "Chenice",
    brandLogo: "/logoChenice.png",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-3.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    title: "KERABONDING MASK",
    formato: "200 ml",
    precio: "€ 14,50",
    subCategory: "RICOSTRUZIONE",
    category: "Capelli",
    brand: "Chenice",
    brandLogo: "/logoChenice.png",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-3.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    title: "HAIR COLOR ACCELERATOR",
    formato: "1 SC x 4Flaconi",
    precio: "€ 59,00",
    subCategory: "HAIR COLOR ACCELERATOR",
    category: "Capelli",
    brand: "Chenice",
    brandLogo: "/logoChenice.png",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-3.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    title: "PEACH SHAMPOO",
    formato: "10 lt. 1 FUSTINO",
    precio: "€ 116,00",
    subCategory: "ALTRO",
    category: "Capelli",
    brand: "Chenice",
    brandLogo: "/logoChenice.png",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-3.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    title: "LIPOSOME HAIR COLOR con ACQUA TERMALE",
    formato: "100ml. 6 TUBO",
    precio: "€ 11,50",
    subCategory: "ALTRO",
    category: "Capelli",
    brand: "Chenice",
    brandLogo: "/logoChenice.png",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-3.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    title: "BOTANICAL HAIR COLOR",
    formato: "100ml. 6 TUBO",
    precio: "€ 12,00",
    subCategory: "ALTRO",
    category: "Capelli",
    brand: "Chenice",
    brandLogo: "/logoChenice.png",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-3.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    title: "VITAMIN COLORS",
    formato: "125ml. 3 FLACONE",
    precio: "€ 21,00",
    subCategory: "ALTRO",
    category: "Capelli",
    brand: "Chenice",
    brandLogo: "/logoChenice.png",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-3.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    title: "OXICREME 20 - 30 - 40 vol. - Active Lotion",
    formato: "1 lt. 6 FLACONE",
    precio: "€ 12,50",
    subCategory: "ALTRO",
    category: "Capelli",
    brand: "Chenice",
    brandLogo: "/logoChenice.png",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-3.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    title: "BLEACH POWDER",
    formato: "500 gr. 1 pz",
    precio: "€ 35,00",
    subCategory: "ALTRO",
    category: "Capelli",
    brand: "Chenice",
    brandLogo: "/logoChenice.png",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-3.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    title: "BLEACH POWDER PLUS",
    formato: "500 gr. 1 pz",
    precio: "€ 36,00",
    subCategory: "ALTRO",
    category: "Capelli",
    brand: "Chenice",
    brandLogo: "/logoChenice.png",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-3.jpg",
    region: ["Abruzzo", "Lazio"],
  },
  {
    title: "DARK DIAMOND",
    formato: "500 gr. 1 pz",
    precio: "€ 37,00",
    subCategory: "ALTRO",
    category: "Capelli",
    brand: "Chenice",
    brandLogo: "/logoChenice.png",
    newFlag: true,
    favorite: true,
    bestseller: false,
    image: "/products/image-3.jpg",
    region: ["Abruzzo", "Lazio"],
  },
];
